-- Fondation --
INSERT INTO Poles (Intitule_Poles, Description_Poles) VALUES 
    ("pspdsa", "Pole sud-Alsace"),
    ("pspdca", "Pole centre-Alsace"),
    ("pspdna", "Pole nord-Alsace")
;  
INSERT INTO Etablissements (Intitule_Etablissements, Adresse_Etablissements, Ville_Etablissements, CodePostal_Etablissements, Cle_Poles) VALUES
    ("Clinique du Diaconat Roosevelt", "14 boulevard Roosevelt", "MULHOUSE", 68100, 1),
    ("Clinique du Diaconat Fonderie", "1 rue Saint Sauveur", "MULHOUSE", 68054, 1),
    ("Hôpital Albert Schweitzer", "201 Avenue d'Alsace", "COLMAR", 68000, 2),
    ("Clinique du Diaconat Colmar", "18 rue Charles Sandheer", "COLMAR", 68000, 2),
    ("Hôpital le Neuenberg", "38 rue Pasteur Hermann", "INGWILLER", 67340, 3),
    ("Saint Jean soins de suite", "1 Grande rue", "SENTHEIM", 68780, 1),
    ("CSMRA Château Walk", "1 rue du château Walk", "HAGUENAU", 67500, 3),
    ("Home du Florimont", "1 rue de la promenade", "INGERSHEIM", 68040, 2),
    ("Diaconat Domisoins", "2 rue Jean Schlumberger", "GUEBWILLER", 68500, 1),
    ("Foyer de l'adolescent", "114 route de Lyon", "ILLKIRCH GRAFFENSTADEN", 67400, 3),
    ("EHPAD Notre Dame des Apôtres", "34 rue Bartholdi", "COLMAR", 68000, 2),
    ("Solidarités Adultes et Familles", "89 Avenue de Colmar", "STRASBOURG", 67100, 2),
    ("Maison de retraite Saint Joseph", "10 rue de l'Abbé Bidaine", "GIROMAGNY", 90200, NULL),
    ("EHPAD les Violettes", "22 Faubourg de Mulhouse", "KINGERSHEIM", 68260, 1)
;
INSERT INTO Services (Intitule_Services, Description_Services) VALUES 
("ACCUEIL"; "Service d'accueil général des visiteurs et patients"),
("ACCUEIL 3"; "Troisième unité d'accueil"),
("ACCUEIL INSCRIP ADMISSION"; "Accueil et inscription pour l'admission des patients"),
("ACCUEIL-STANDARD"; "Service d'accueil et gestion des appels téléphoniques"),
("ADMINISTRATION"; "Service général de gestion administrative"),
("Administration"; "Gestion des procédures administratives courantes"),
("ADMINISTRATION ENCADREMENT"; "Service d'encadrement administratif"),
("ADMISSIONS"; "Service des admissions hospitalières"),
("AHS"; "Assistance Hôtelière et Soins"),
("AHS MED 1 / 2"; "Service d'AHS Médecine, unité 1 et 2"),
("AHS MED 3/ USMC / USIC"; "Unité de soins intensifs et chirurgie"),
("AMBULATOIRE"; "Service ambulatoire pour les consultations externes"),
("ANESTHESIE"; "Service d'anesthésie pour les interventions chirurgicales"),
("ARCHIVES"; "Service de gestion et stockage des archives"),
("AS NUIT SOINS"; "Aide-soignant(e) pour les soins de nuit"),
("ASH CDD"; "Aide-soignant hospitalier en contrat à durée déterminée"),
("ASPREMA"; "Service d'aspiration et soins respiratoires"),
("AUMONERIE"; "Service d'aumônerie pour l'assistance spirituelle"),
("AUMONERIE DIACONAT"; "Aumônerie spécifique au Diaconat"),
("BIOMEDICAL"; "Service des équipements biomédicaux"),
("BIONETTOYAGE"; "Service de bionettoyage des locaux"),
("BLOC ANGIO"; "Bloc opératoire dédié à l'angiologie"),
("BLOC OPERATOIRE"; "Bloc opératoire principal"),
("BRANCARDIER CHIR"; "Brancardier pour le service de chirurgie"),
("CARDIO A"; "Service de cardiologie A"),
("CARDIO B"; "Service de cardiologie B"),
("CARDIOLOGIE"; "Service de traitement des maladies cardiaques"),
("CDD ADM"; "Contrat à durée déterminée administratif"),
("CDS PHI"; "Centre de soins phi"),
("CENTRE DE PERINATALITE"; "Centre spécialisé en périnatalité"),
("CENTRE RESSOURCE TERRITORIALE"; "Centre de ressources pour le territoire"),
("CHAUFFEURS"; "Service de chauffeurs pour le transport médical"),
("CHIR AMBULATOIRE"; "Chirurgie ambulatoire pour interventions légères"),
("CHIRURGIE 1"; "Service de chirurgie, unité 1"),
("CHIRURGIE 2"; "Service de chirurgie, unité 2"),
("CHIRURGIE 3"; "Service de chirurgie, unité 3"),
("CHIRURGIE 4"; "Service de chirurgie, unité 4"),
("CHIRURGIE A"; "Chirurgie, section A"),
("CHIRURGIE B"; "Chirurgie, section B"),
("CHIRURGIE C"; "Chirurgie, section C"),
("CHIRURGIE D"; "Chirurgie, section D"),
("CHIRURGIE E"; "Chirurgie, section E"),
("COMMINUCATION ARCHIVES"; "Service de communication et gestion des archives"),
("COMPTABILITE"; "Service de comptabilité"),
("COMPTABILITE CAISSE"; "Comptabilité et gestion des caisses"),
("CONCOURS AES"; "Concours d'admission aux écoles AES"),
("CONSULTATION CANCERO"; "Consultation dédiée aux patients atteints de cancer"),
("CONSULTATION EXTERNE"; "Consultations pour les patients externes"),
("CONTROLE DE GESTION"; "Service de contrôle de gestion hospitalière"),
("CRECHE"; "Service de crèche pour le personnel hospitalier"),
("DIETETIQUE"; "Service de diététique pour le suivi nutritionnel des patients"),
("DIETETIQUE CDD"; "Service de diététique sous contrat à durée déterminée"),
("DIRECTION"; "Direction générale de l'établissement"),
("DIRECTION DES SOINS"; "Direction des soins infirmiers et médicaux"),
("DOMISOINS GUEBWILLER"; "Soins à domicile à Guebwiller"),
("DOMISOINS VIEUX THANN"; "Soins à domicile à Vieux Thann"),
("DPI"; "Dossier patient informatisé"),
("DSIO"; "Direction des systèmes d'information et de l'organisation"),
("ECOLE AMP"; "École pour les aides médico-psychologiques"),
("ECOLE AP"; "École pour les aides-soignants"),
("ECOLE AS"; "École d'aide-soignants"),
("ECOLE FORMATION INTERNE"; "École de formation interne pour le personnel médical"),
("ECOLE OUTRE MER"; "Formation pour les personnels d'outre-mer"),
("ECOLE VAE"; "Validation des acquis de l'expérience"),
("EHPAD BETHANIE"; "EHPAD situé à Bethanie"),
("EHPAD CHAMP FLEURI"; "EHPAD du Champ Fleuri"),
("EHPAD EMMAUS"; "EHPAD Emmaüs"),
("EHPAD ETAGE 1 CLINIQUE"; "Premier étage de la clinique EHPAD"),
("EHPAD LES VIOLETTES"; "EHPAD Les Violettes"),
("EHPAD RENE VOGEL"; "EHPAD René Vogel"),
("EHPAD SIMEON"; "EHPAD Siméon"),
("EN FORMATION"; "Personnel en formation professionnelle"),
("ENDOSCOPIE"; "Service de diagnostic par endoscopie"),
("ENI"; "Service ENI (Examens Non-Invasifs)"),
("ENTRETIEN CDD"; "Service d'entretien sous contrat à durée déterminée"),
("EXPLORAT FONCTIONNELLES"; "Service d'explorations fonctionnelles"),
("FACTURATION"; "Service de facturation des soins"),
("FAE ILLKIRCH"; "Formation à l'aide-soignante d'Illkirch"),
("GAP"; "Groupe d'aide et prévention"),
("GYNECOLOGIE"; "Service de gynécologie"),
("HABITAT INCLUSIF"; "Service d'habitat inclusif pour les patients"),
("HOME DU FLORIMONT"; "Service de soins au Home du Florimont"),
("HOPITAL DE JOUR"; "Hôpital de jour pour les consultations"),
("HOPITAL DE SEMAINE"; "Hôpital de semaine pour les hospitalisations légères"),
("HYGIENE HOSPITALIERE"; "Service d'hygiène hospitalière"),
("IFSI"; "Institut de formation en soins infirmiers"),
("INFORMATIQUE"; "Service informatique"),
("INTERVENANTES"; "Personnel intervenant en soins"),
("KINESITHERAPIE"; "Service de kinésithérapie"),
("KINESITHERAPIE CDD"; "Kinésithérapie sous contrat à durée déterminée"),
("KINESITHERAPIE ERGOTHERAPIE"; "Kinésithérapie et ergothérapie combinées"),
("LABORATOIRE FONDERIE"; "Laboratoire de la fonderie"),
("LABORATOIRE ROOSEVELT"; "Laboratoire Roosevelt"),
("LASER DERMATOLOGIQUE"; "Service de dermatologie laser"),
("LINGERIE"; "Service de lingerie hospitalière"),
("LINGERIE CDD"; "Lingerie sous contrat à durée déterminée"),
("LOFT"; "Service des lofts médicaux"),
("MAGASIN"; "Service du magasin hospitalier"),
("MAINTENANCE"; "Service de maintenance des équipements"),
("MATERNITE"; "Service de maternité"),
("MEDECINE"; "Médecine générale"),
("MEDECINE 1"; "Médecine générale, unité 1"),
("MEDECINE 2"; "Médecine générale, unité 2"),
("MEDECINE 3"; "Médecine générale, unité 3"),
("MEDECINE GERIATRIQUE"; "Médecine gériatrique"),
("MEDECINE NUCLEAIRE"; "Médecine nucléaire"),
("MEDECINE POLYVALENTE"; "Médecine polyvalente"),
("MR"; "Médecine de rééducation"),
("NEO NAT"; "Néonatologie"),
("PAHC AS"; "Programme d'accompagnement pour les aides-soignants"),
("PC SECURITE"; "Poste de contrôle sécurité"),
("PEDIATRE"; "Service pédiatrique"),
("PERSONNEL AIDE SOIGNANT CDD"; "Aides-soignants sous contrat à durée déterminée"),
("PERSONNEL HOTELIER"; "Personnel hôtelier du centre hospitalier"),
("PERSONNEL MEDICAL"; "Personnel médical général"),
("PERSONNEL MEDICAL CDD"; "Personnel médical sous contrat à durée déterminée"),
("PHARMACIE"; "Service de pharmacie hospitalière"),
("PHI"; "Service PHI (Pharmacie à usage intérieur)"),
("PMSI"; "Programme de médicalisation des systèmes d'information"),
("PNA CARDIO"; "Préparation non activée - service cardiologique"),
("PNA SOINS"; "Préparation non activée - service de soins"),
("PNA SOINS NUIT"; "Préparation non activée pour soins de nuit"),
("PNEUMOLOGIE"; "Service de pneumologie"),
("POLICLINIQUE"; "Polyclinique pour consultations diverses"),
("POOL DE REMPLACEMENT"; "Service de remplacement pour les soins"),
("POUPONNIERE"; "Pouponnière hospitalière"),
("PRE-ADMISSIONS"; "Service de pré-admissions hospitalières"),
("PTLAM COLMAR"; "PTLAM à Colmar"),
("QUALITE HYGIENE"; "Service de qualité et d'hygiène hospitalière"),
("RADIOLOGIE"; "Service de radiologie"),
("RECEPTION LOGISTIQUE"; "Réception et gestion logistique des biens hospitaliers"),
("RESSOURCES HUMAINES"; "Service des ressources humaines"),
("RESTAURATION CUISINE"; "Service de restauration et cuisine"),
("RESTAURATION CUISINE CDD"; "Restauration sous contrat à durée déterminée"),
("RESTAURATION SALLE+CAFETER.CDD"; "Restauration en salle et cafétéria sous CDD"),
("RESTAURATION SERV.SALLE+CAFET"; "Service en salle et cafétéria"),
("SAMNA HAGUENAU"; "SAMNA situé à Haguenau"),
("SAMNA STRASBOURG"; "SAMNA situé à Strasbourg"),
("SCES EN COURS DE FERMETURE"; "Services en cours de fermeture"),
("SEC  ANESTHESIE"; "Secrétariat pour le service d'anesthésie"),
("SEC BLOC OPERATOIRE"; "Secrétariat du bloc opératoire"),
("SEC CHIR AMBULATOIRE"; "Secrétariat de la chirurgie ambulatoire"),
("SEC CHIR DIGESTIVE"; "Secrétariat de la chirurgie digestive"),
("SEC CHIR VASCULAIRE"; "Secrétariat de la chirurgie vasculaire"),
("SEC DIABETO"; "Secrétariat pour le service de diabétologie"),
("SEC ENDOSCOPIE"; "Secrétariat du service d'endoscopie"),
("SEC ENI"; "Secrétariat des examens non-invasifs"),
("SEC GERIATRIE"; "Secrétariat du service de gériatrie"),
("SEC GYNECO"; "Secrétariat du service de gynécologie"),
("SEC HOP DE JOUR"; "Secrétariat de l'hôpital de jour"),
("SEC ORTHO"; "Secrétariat pour le service orthopédique"),
("SEC POLICLINIQUE"; "Secrétariat pour la polyclinique"),
("SEC RADIO"; "Secrétariat du service de radiologie"),
("SEC RADIO INTERV"; "Secrétariat de radiologie interventionnelle"),
("SEC RHUMATOLOGIE"; "Secrétariat pour le service de rhumatologie"),
("SEC SICS"; "Secrétariat pour le SICS"),
("SEC USIC"; "Secrétariat de l'unité de soins intensifs cardiologiques"),
("SECRETARIAT CARDIO"; "Secrétariat pour le service de cardiologie"),
("SECRETARIAT DE DIRECTION"; "Secrétariat général de la direction"),
("SECRETARIAT MEDICAL"; "Secrétariat médical général"),
("SERVICE ECONOMIQUE"; "Service de gestion économique hospitalière"),
("Service éducatif"; "Service éducatif interne pour les jeunes patients"),
("SERVICE MEDICAL"; "Service médical général"),
("SERVICE SOCIAL"; "Service d'assistance sociale"),
("SERVICE SOIGNANT"; "Service de soins aux patients"),
("SERVICE SOINS IDE CDD"; "Service de soins IDE sous contrat à durée déterminée"),
("SERVICES FINANCIERS"; "Service de gestion financière"),
("SERVICES GENERAUX"; "Services généraux pour la gestion quotidienne"),
("SERVICES TECHNIQUES"; "Services techniques et maintenance"),
("SICS DIACONAT"; "SICS pour le Diaconat"),
("SICS HAS"; "SICS pour l'HAS"),
("SICS MEDICO SOCIAL"; "SICS pour le secteur médico-social"),
("SIEGE"; "Siège de l'administration centrale"),
("SOINS ENCADREMENT"; "Encadrement des soins médicaux"),
("SSR"; "Soins de suite et de réadaptation"),
("SSR CARDIO VASCUL RESPIRATOIRE"; "SSR spécialisé en cardiologie, vasculaire et respiratoire"),
("STERILISATION"; "Service de stérilisation des équipements"),
("TRAVAUX"; "Service des travaux et rénovation hospitalière"),
("UNITE DE SURVEILLANCE CONTINUE"; "Unité de surveillance continue des patients"),
("URGENCES"; "Service des urgences hospitalières"),
("URGENCES CARDIO"; "Urgences cardiologiques"),
("USC"; "Unité de soins continus"),
("USIC"; "Unité de soins intensifs en cardiologie"),
("USICAR"; "Unité de soins intensifs en cardiologie et réanimation"),
("USLD BETHANIE"; "Unité de soins longue durée à Bethanie"),
("USMC"; "Unité de soins de médecine continue"),
("USSR"; "Unité de soins de suite et de réadaptation");
