-- On insère les pôles de la Fondation --
INSERT INTO Poles (Intitule_Poles, Description_Poles) VALUES 
    ("pspdsa", "Pole sud-Alsace"),
    ("pspdca", "Pole centre-Alsace"),
    ("pspdna", "Pole nord-Alsace")
;  
-- On insère les Etablissemnts de la Fondation --
INSERT INTO etablissements (Intitule_Etablissements, Adresse_Etablissements, Ville_Etablissements, CodePostal_Etablissements, Cle_Poles) VALUES
    ("Clinique du Diaconat Roosevelt", "14 boulevard Roosevelt", "MULHOUSE", 68100, 1),
    ("Clinique du Diaconat Fonderie", "1 rue Saint Sauveur", "MULHOUSE", 68054, 1),
    ("Hôpital Albert Schweitzer", "201 Avenue d'Alsace", "COLMAR", 68000, 2),
    ("Clinique du Diaconat Colmar", "18 rue Charles Sandheer", "COLMAR", 68000, 2),
    ("Hôpital le Neuenberg", "38 rue Pasteur Hermann", "INGWILLER", 67340, 3),
    ("Saint Jean soins de suite", "1 Grande rue", "SENTHEIM", 68780, 1),
    ("CSMRA Château Walk", "1 rue du château Walk", "HAGUENAU", 67500, 3),
    ("Home du Florimont", "1 rue de la promenade", "INGERSHEIM", 68040, 2),
    ("Diaconat Domisoins", "2 rue Jean Schlumberger", "GUEBWILLER", 68500, 1),
    ("Foyer de l'adolescent", "114 route de Lyon", "ILLKIRCH GRAFFENSTADEN", 67400, 3),
    ("EHPAD Notre Dame des Apôtres", "34 rue Bartholdi", "COLMAR", 68000, 2),
    ("Solidarités Adultes et Familles", "89 Avenue de Colmar", "STRASBOURG", 67100, 2),
    ("Maison de retraite Saint Joseph", "10 rue de l'Abbé Bidaine", "GIROMAGNY", 90200, NULL),
    ("EHPAD les Violettes", "22 Faubourg de Mulhouse", "KINGERSHEIM", 68260, 1)
;
-- On insère les Services de la Fondation --
INSERT INTO `services` (`Intitule_Services`, `Cle_Etablissements`) VALUES
    -- Clinique du Diaconat Roosevelt -- 
    ("STERILISATION - Diaconat Roosevelt", 1),
    ("BLOC OPERATOIRE - Diaconat Roosevelt", 1),
    ("ANESTHESIE - Diaconat Roosevelt", 1),
    ("BLOC ANGIO - Diaconat Roosevelt", 1),
    ("ENDOSCOPIE - Diaconat Roosevelt", 1),
    ("BRANCARDIER CHIR - Diaconat Roosevelt", 1),
    ("HOPITAL DE SEMAINE - Diaconat Roosevelt", 1),
    ("AMBULATOIRE - Diaconat Roosevelt", 1),
    ("SOINS ENCADREMENT - Diaconat Roosevelt", 1),
    ("PRE-ADMISSIONS - Diaconat Roosevelt", 1),
    ("EN FORMATION - Diaconat Roosevelt", 1),
    ("CHIRURGIE A - Diaconat Roosevelt", 1),
    ("CHIRURGIE D - Diaconat Roosevelt", 1),
    ("CHIRURGIE B - Diaconat Roosevelt", 1),
    ("CHIRURGIE C - Diaconat Roosevelt", 1),
    ("CHIRURGIE E - Diaconat Roosevelt", 1),
    ("PNA SOINS - Diaconat Roosevelt", 1),
    ("PNA SOINS NUIT - Diaconat Roosevelt", 1),
    ("MATERNITE - Diaconat Roosevelt", 1),
    ("GYNECOLOGIE - Diaconat Roosevelt", 1),
    ("CENTRE DE PERINATALITE - Diaconat Roosevelt", 1),
    ("MEDECINE - Diaconat Roosevelt", 1),
    ("MEDECINE POLYVALENTE - Diaconat Roosevelt", 1),
    ("MEDECINE NUCLEAIRE - Diaconat Roosevelt", 1),
    ("CRECHE - Diaconat Roosevelt", 1),
    ("CARDIOLOGIE - Diaconat Roosevelt", 1),
    ("USIC - Diaconat Roosevelt", 1),
    ("ASPREMA - Diaconat Roosevelt", 1),
    ("INTERVENANTES - Diaconat Roosevelt", 1),
    ("KINESITHERAPIE - Diaconat Roosevelt", 1),
    ("PNEUMOLOGIE - Diaconat Roosevelt", 1),
    ("LABORATOIRE ROOSEVELT - Diaconat Roosevelt", 1),
    ("LABORATOIRE FONDERIE - Diaconat Roosevelt", 1),
    ("PTLAM COLMAR - Diaconat Roosevelt", 1),
    ("POLICLINIQUE - Diaconat Roosevelt", 1),
    ("CONSULTATION CANCERO - Diaconat Roosevelt", 1),
    ("LASER DERMATOLOGIQUE - Diaconat Roosevelt", 1),
    ("RADIOLOGIE - Diaconat Roosevelt", 1),
    ("HABITAT INCLUSIF - Diaconat Roosevelt", 1),
    ("RESTAURATION CUISINE - Diaconat Roosevelt", 1),
    ("BIOMEDICAL - Diaconat Roosevelt", 1),
    ("SERVICES TECHNIQUES - Diaconat Roosevelt", 1),
    ("RECEPTION LOGISTIQUE - Diaconat Roosevelt", 1),
    ("ACCUEIL INSCRIP ADMISSION - Diaconat Roosevelt", 1),
    ("PMSI - DIM - Diaconat Roosevelt", 1),
    ("SECRETARIAT MEDICAL - Diaconat Roosevelt", 1),
    ("IFSI - Diaconat Roosevelt", 1),
    ("ECOLE AS - Diaconat Roosevelt", 1),
    ("AS NUIT SOINS - Diaconat Roosevelt", 1),
    ("PHARMACIE - Diaconat Roosevelt", 1),
    ("COMMINUCATION ARCHIVES - Diaconat Roosevelt", 1),
    ("COMPTABILITE CAISSE - Diaconat Roosevelt", 1),
    ("FACTURATION - Diaconat Roosevelt", 1),
    ("RESSOURCES HUMAINES - Diaconat Roosevelt", 1),
    ("QUALITE HYGIENE - Diaconat Roosevelt", 1),
    ("DIRECTION - Diaconat Roosevelt", 1),
    ("ADMINISTRATION ENCADREMENT - Diaconat Roosevelt", 1),
    ("ADMINISTRATION - Diaconat Roosevelt", 1),
    ("CONTROLE DE GESTION - Diaconat Roosevelt", 1),
    ("INFORMATIQUE - Diaconat Roosevelt", 1),
    ("LINGERIE - Diaconat Roosevelt", 1),
    ("PERSONNEL HOTELIER - Diaconat Roosevelt", 1),

    -- Clinique du Diaconat Fonderie --
    ("STERILISATION - Diaconat Fonderie", 2),
    ("BLOC OPERATOIRE - Diaconat Fonderie", 2),
    ("ANESTHESIE - Diaconat Fonderie", 2),
    ("BLOC ANGIO - Diaconat Fonderie", 2),
    ("UNITE DE SURVEILLANCE CONTINUE - Diaconat Fonderie", 2),
    ("HOPITAL DE JOUR - Diaconat Fonderie", 2),
    ("SOINS ENCADREMENT - Diaconat Fonderie", 2),
    ("EN FORMATION - Diaconat Fonderie", 2),
    ("CHIRURGIE 1 - Diaconat Fonderie", 2),
    ("CHIRURGIE 2 - Diaconat Fonderie", 2),
    ("PNA SOINS NUIT - Diaconat Fonderie", 2),
    ("MATERNITE - Diaconat Fonderie", 2),
    ("NEO NAT - Diaconat Fonderie", 2),
    ("POUPONNIERE - Diaconat Fonderie", 2),
    ("CARDIO A - Diaconat Fonderie", 2),
    ("CARDIO B - Diaconat Fonderie", 2),
    ("EXPLORAT FONCTIONNELLES - Diaconat Fonderie", 2),
    ("PNA CARDIO - Diaconat Fonderie", 2),
    ("SECRETARIAT CARDIO - Diaconat Fonderie", 2),
    ("USIC - Diaconat Fonderie", 2),
    ("USC - Diaconat Fonderie", 2),
    ("DPI - Diaconat Fonderie", 2),
    ("URGENCES - Diaconat Fonderie", 2),
    ("URGENCES CARDIO - Diaconat Fonderie", 2),
    ("CONSULTATION EXTERNE - Diaconat Fonderie", 2),
    ("BIOMEDICAL - Diaconat Fonderie", 2),
    ("SERVICES TECHNIQUES - Diaconat Fonderie", 2),
    ("RECEPTION LOGISTIQUE - Diaconat Fonderie", 2),
    ("ACCUEIL INSCRIP ADMISSION - Diaconat Fonderie", 2),
    ("PMSI - DIM - Diaconat Fonderie", 2),
    ("AS NUIT SOINS - Diaconat Fonderie", 2),
    ("PHARMACIE - Diaconat Fonderie", 2),
    ("ARCHIVES - Diaconat Fonderie", 2),
    ("COMPTABILITE - Diaconat Fonderie", 2),
    ("FACTURATION - Diaconat Fonderie", 2),
    ("QUALITE HYGIENE - Diaconat Fonderie", 2),
    ("DIRECTION - Diaconat Fonderie", 2),
    ("ADMINISTRATION ENCADREMENT - Diaconat Fonderie", 2),
    ("ADMINISTRATION - Diaconat Fonderie", 2),
    ("LINGERIE - Diaconat Fonderie", 2),
    ("PERSONNEL HOTELIER - Diaconat Fonderie", 2),

    -- Hôpital Albert Schweitze --
    ("STERILISATION - Albert Schweitzer", 3),
    ("BLOC OPERATOIRE - Albert Schweitzer", 3),
    ("ANESTHESIE - Albert Schweitzer", 3),
    ("BLOC ANGIO - Albert Schweitzer", 3),
    ("ENDOSCOPIE - Albert Schweitzer", 3),
    ("SEC BLOC OPERATOIRE - Albert Schweitzer", 3),
    ("SEC  ANESTHESIE - Albert Schweitzer", 3),
    ("SEC ENDOSCOPIE - Albert Schweitzer", 3),
    ("BRANCARDIER CHIR - Albert Schweitzer", 3),
    ("SOINS ENCADREMENT - Albert Schweitzer", 3),
    ("EN FORMATION - Albert Schweitzer", 3),
    ("CHIR AMBULATOIRE - Albert Schweitzer", 3),
    ("CHIRURGIE 1 - Albert Schweitzer", 3),
    ("CHIRURGIE 2 - Albert Schweitzer", 3),
    ("CHIRURGIE 3 - Albert Schweitzer", 3),
    ("CHIRURGIE 4 - Albert Schweitzer", 3),
    ("SEC CHIR AMBULATOIRE - Albert Schweitzer", 3),
    ("SEC CHIR VASCULAIRE - Albert Schweitzer", 3),
    ("SEC CHIR DIGESTIVE - Albert Schweitzer", 3),
    ("GYNECOLOGIE - Albert Schweitzer", 3),
    ("PEDIATRE - Albert Schweitzer", 3),
    ("SEC GYNECO - Albert Schweitzer", 3),
    ("MEDECINE GERIATRIQUE - Albert Schweitzer", 3),
    ("MEDECINE 1 - Albert Schweitzer", 3),
    ("MEDECINE 2 - Albert Schweitzer", 3),
    ("MEDECINE 3 - Albert Schweitzer", 3),
    ("SECRETARIAT CARDIO - Albert Schweitzer", 3),
    ("USICAR - Albert Schweitzer", 3),
    ("USIC - Albert Schweitzer", 3),
    ("SEC USIC - Albert Schweitzer", 3),
    ("DSIO - Albert Schweitzer", 3),
    ("ENI - Albert Schweitzer", 3),
    ("GAP - Albert Schweitzer", 3),
    ("HYGIENE HOSPITALIERE - Albert Schweitzer", 3),
    ("USMC - Albert Schweitzer", 3),
    ("SEC RHUMATOLOGIE - Albert Schweitzer", 3),
    ("SEC ENI - Albert Schweitzer", 3),
    ("SEC ORTHO - Albert Schweitzer", 3),
    ("KINESITHERAPIE - Albert Schweitzer", 3),
    ("SSR CARDIO VASCUL RESPIRATOIRE - Albert Schweitzer", 3),
    ("LABORATOIRE ROOSEVELT - Albert Schweitzer", 3),
    ("POLICLINIQUE - Albert Schweitzer", 3),
    ("SEC POLICLINIQUE - Albert Schweitzer", 3),
    ("SEC SICS - Albert Schweitzer", 3),
    ("SEC DIABETO - Albert Schweitzer", 3),
    ("SICS HAS - Albert Schweitzer", 3),
    ("SEC RADIO - Albert Schweitzer", 3),
    ("RADIOLOGIE - Albert Schweitzer", 3),
    ("SEC RADIO INTERV - Albert Schweitzer", 3),
    ("DIETETIQUE - Albert Schweitzer", 3),
    ("BIOMEDICAL - Albert Schweitzer", 3),
    ("SERVICES TECHNIQUES - Albert Schweitzer", 3),
    ("RECEPTION LOGISTIQUE - Albert Schweitzer", 3),
    ("MAGASIN - Albert Schweitzer", 3),
    ("TRAVAUX - Albert Schweitzer", 3),
    ("PC SECURITE - Albert Schweitzer", 3),
    ("ACCUEIL 3 - Albert Schweitzer", 3),
    ("ACCUEIL-STANDARD - Albert Schweitzer", 3),
    ("ADMISSIONS - Albert Schweitzer", 3),
    ("PMSI - DIM - Albert Schweitzer", 3),
    ("CONCOURS AES - Albert Schweitzer", 3),
    ("EHPAD ETAGE 1 CLINIQUE - Albert Schweitzer", 3),
    ("PHARMACIE - Albert Schweitzer", 3),
    ("SERVICE ECONOMIQUE - Albert Schweitzer", 3),
    ("ARCHIVES - Albert Schweitzer", 3),
    ("AUMONERIE - Albert Schweitzer", 3),
    ("FACTURATION - Albert Schweitzer", 3),
    ("RESSOURCES HUMAINES - Albert Schweitzer", 3),
    ("QUALITE HYGIENE - Albert Schweitzer", 3),
    ("DIRECTION - Albert Schweitzer", 3),
    ("SERVICES FINANCIERS - Albert Schweitzer", 3),
    ("AUMONERIE DIACONAT - Albert Schweitzer", 3),
    ("AHS - LINGERIE - Albert Schweitzer", 3),
    ("AHS - CHIR AMBU - Albert Schweitzer", 3),
    ("AHS - CHIR AMBUL/CHIR2 - Albert Schweitzer", 3),
    ("AHS - CHIR3/4 - Albert Schweitzer", 3),
    ("AHS - MED1/2/USIC - Albert Schweitzer", 3),
    ("AHS - MED3/USMC - Albert Schweitzer", 3),
    ("AHS - MED3/USMC - Albert Schweitzer", 3),
    ("AHS - SICS HAS - Albert Schweitzer", 3),
    ("AHS - SODEXO HAS - Albert Schweitzer", 3),
    ("AHS - SODEXO DIACONAT - Albert Schweitzer", 3),
    ("AHS - ZONE DIVERS - Albert Schweitzer", 3),
    ("AHS MED 1 / 2 - Albert Schweitzer", 3),
    ("AHS MED 3/ USMC / USIC - Albert Schweitzer", 3),

    -- Clinique du Diaconat Colmar --
    ("SERVICE ECONOMIQUE - Diaconat Colmar", 4),
    ("AHS - SICS HAS - Diaconat Colmar", 4),
    ("AHS - SODEXO DIACONAT - Diaconat Colmar", 4),
    ("HOPITAL DE JOUR - Diaconat Colmar", 4),
    ("SEC HOP DE JOUR - Diaconat Colmar", 4),
    ("EN FORMATION - Diaconat Colmar", 4),
    ("MEDECINE - Diaconat Colmar", 4),
    ("MEDECINE POLYVALENTE - Diaconat Colmar", 4),
    ("CARDIOLOGIE - Diaconat Colmar", 4),
    ("SEC GERIATRIE - Diaconat Colmar", 4),
    ("KINESITHERAPIE - Diaconat Colmar", 4),
    ("SICS DIACONAT - Diaconat Colmar", 4),
    ("SICS HAS - Diaconat Colmar", 4),
    ("SICS MEDICO SOCIAL - Diaconat Colmar", 4),
    ("SSR - Diaconat Colmar", 4),
    ("CENTRE RESSOURCE TERRITORIALE - Diaconat Colmar", 4),
    ("DIETETIQUE - Diaconat Colmar", 4),
    ("SERVICES TECHNIQUES - Diaconat Colmar", 4),
    ("TRAVAUX - Diaconat Colmar", 4),
    ("ACCUEIL 3 - Diaconat Colmar", 4),
    ("ACCUEIL - STANDARD - Diaconat Colmar", 4),
    ("CONCOURS AES - Diaconat Colmar", 4),
    ("ECOLE AP - Diaconat Colmar", 4),
    ("ECOLE AS - Diaconat Colmar", 4),
    ("ECOLE FORMATION INTERNE - Diaconat Colmar", 4),
    ("ECOLE OUTRE MER - Diaconat Colmar", 4),
    ("ECOLE VAE - Diaconat Colmar", 4),
    ("ECOLE AMP - Diaconat Colmar", 4),
    ("EHPAD ETAGE 1 CLINIQUE - Diaconat Colmar", 4),
    ("EHPAD RENE VOGEL - Diaconat Colmar", 4),
    ("DIRECTION DES SOINS - Diaconat Colmar", 4),
    ("ADMINISTRATION - Diaconat Colmar", 4),
    ("SERVICES GENERAUX - Diaconat Colmar", 4),

    -- Hôpital le Neuenberg -- 
    ("EN FORMATION - Neuenberg", 5),
    ("CENTRE DE PERINATALITE - Neuenberg", 5),
    ("MEDECINE - Neuenberg", 5),
    ("POOL DE REMPLACEMENT - Neuenberg", 5),
    ("SCES EN COURS DE FERMETURE - Neuenberg", 5),
    ("USLD BETHANIE - Neuenberg", 5),
    ("USSR - Neuenberg", 5),
    ("RADIOLOGIE - Neuenberg", 5),
    ("RESTAURATION CUISINE - Neuenberg", 5),
    ("CHAUFFEURS - Neuenberg", 5),
    ("ACCUEIL - MR - Neuenberg", 5),
    ("ACCUEIL - STANDARD - Neuenberg", 5),
    ("ADMISSIONS - Neuenberg", 5),
    ("ECOLE FORMATION INTERNE - Neuenberg", 5),
    ("EHPAD BETHANIE - Neuenberg", 5),
    ("EHPAD CHAMP FLEURI - Neuenberg", 5),
    ("EHPAD EMMAUS - Neuenberg", 5),
    ("EHPAD SIMEON - Neuenberg", 5),
    ("PHARMACIE - Neuenberg", 5),
    ("SERVICE ECONOMIQUE - Neuenberg", 5),
    ("COMPTABILITE - Neuenberg", 5),
    ("RESSOURCES HUMAINES - Neuenberg", 5),
    ("DIRECTION - Neuenberg", 5),
    ("SECRETARIAT DE DIRECTION - Neuenberg", 5),
    ("SERVICES GENERAUX - Neuenberg", 5),
    ("LINGERIE - Neuenberg", 5),
    ("BIONETTOYAGE - Neuenberg", 5),

    -- Saint Jean soins de suite --
    ("EN FORMATION - Saint Jean", 6),
    ("KINESITHERAPIE - Saint Jean", 6),
    ("KINESITHERAPIE CDD - Saint Jean", 6),
    ("KINESITHERAPIE ERGOTHERAPIE - Saint Jean", 6),
    ("SERVICE SOIGNANT - Saint Jean", 6),
    ("SERVICE MEDICAL - Saint Jean", 6),
    ("SERVICE SOCIAL - Saint Jean", 6),
    ("SERVICE SOINS IDE CDD - Saint Jean", 6),
    ("RESTAURATION CUISINE - Saint Jean", 6),
    ("RESTAURATION CUISINE CDD - Saint Jean", 6),
    ("RESTAURATION SALLE+CAFETER.CDD - Saint Jean", 6),
    ("RESTAURATION SERV.SALLE+CAFET - Saint Jean", 6),
    ("DIETETIQUE - Saint Jean", 6),
    ("DIETETIQUE CDD - Saint Jean", 6),
    ("SERVICES TECHNIQUES - Saint Jean", 6),
    ("MAINTENANCE - Saint Jean", 6),
    ("ENTRETIEN CDD - Saint Jean", 6),
    ("PERSONNEL AIDE SOIGNANT CDD - Saint Jean", 6),
    ("PERSONNEL MEDICAL - Saint Jean", 6),
    ("PERSONNEL MEDICAL CDD - Saint Jean", 6),
    ("DIRECTION - Saint Jean", 6),
    ("ADMINISTRATION - Saint Jean", 6),
    ("CDD ADM - Saint Jean", 6),
    ("LINGERIE - Saint Jean", 6),
    ("LINGERIE CDD - Saint Jean", 6),
    ("PERSONNEL HOTELIER - Saint Jean", 6),
    ("ASH CDD - Saint Jean", 6),

    -- CSMRA Château Walk --
    ("EN FORMATION - Château Walk", 7),
    ("SERVICE SOIGNANT - Château Walk", 7),
    ("SERVICE MEDICAL - Château Walk", 7),
    ("SERVICE SOCIAL - Château Walk", 7),
    ("Service éducatif - Château Walk", 7),
    ("Administration - Château Walk", 7),

    -- Home du Florimont --
    ("EN FORMATION - Home du Florimont", 8),
    ("TRAVAUX - Home du Florimont", 8),
    ("CONCOURS AES - Home du Florimont", 8),
    ("EHPAD ETAGE 1 CLINIQUE - Home du Florimont", 8),
    ("HOME DU FLORIMONT - Home du Florimont", 8),
    ("AUMONERIE - Home du Florimont", 8),

    -- Diaconat Domisoins -- 
    ("EN FORMATION - Diaconat Domisoins", 9), 
    ("SERVICES TECHNIQUES - Diaconat Domisoins", 9), 
    ("DOMISOINS GUEBWILLER - Diaconat Domisoins", 9), 
    ("DOMISOINS VIEUX THANN - Diaconat Domisoins", 9), 
    ("ADMINISTRATION - Diaconat Domisoins", 9), 

    -- Foyer de l'adolescent --
    ("EN FORMATION - Foyer de l'ado", 10),
    ("SERVICES TECHNIQUES - Foyer de l'ado", 10),
    ("SAMNA HAGUENAU - Foyer de l'ado", 10),
    ("SAMNA STRASBOURG - Foyer de l'ado", 10),
    ("FAE ILLKIRCH - Foyer de l'ado", 10),
    ("DIRECTION - Foyer de l'ado", 10),

    -- EHPAD Notre Dame des Apôtres -- 
    ("EN FORMATION - Notre dame", 11),
    ("SERVICES TECHNIQUES - Notre dame", 11),

    -- Solidarités Adultes et Familles --
    ("EN FORMATION - Diaconat SAF", 12),
    ("MAINTENANCE - Diaconat SAF", 12),
    ("PAHC AS - Diaconat SAF", 12),
    ("LOFT - Diaconat SAF", 12),
    ("PHI - Diaconat SAF", 12),
    ("MR - Diaconat SAF", 12),
    ("CDS PHI - Diaconat SAF", 12),
    ("DIRECTION - Diaconat SAF", 12),
    ("SIEGE - Diaconat SAF", 12),

    -- Maison de retraite Saint Joseph --
    ("EN FORMATION - Saint Joseph", 13),

    -- EHPAD les Violettes --
    ("EN FORMATION - Les violettes", 14),
    ("EHPAD LES VIOLETTES - Les violettes", 14),
    ("DIRECTION - Les violettes", 14)
;

-- On insère les diplomes --
INSERT INTO `diplomes` (`Intitule_Diplomes`, `Description_Diplomes`) VALUES
    ("Diplôme d'état français d'infirmier", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IDE"),
    ("Diplôme d'état français d'infirmier anesthésiste", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IADE"),
    ("Diplôme d'état français d'infirmier de bloc opératoire", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IBODE"),
    ("Diplôme d'état français de cadre de santé", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: CS"),
    ("Diplôme d'état français d'infirmier puericulteur", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IP"),
    ("Diplôme d'état français de masseur-kinesitherapeute", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: KINE"),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession d'infirmier", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IDE"),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession de masseur-kinesitherapeute", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: KINE"),
    ("Autorisation ministérielle de plein exercice", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Aide soignant D.E.", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: AS"),
    ("Sage Femme D.E.", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: SF"),
    ("Diplôme d’études spécialisées de médecine générale", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: Médecin"),
    ("Diplôme d’Etat de docteur en médecine", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: Médecin"),
    ("Diplôme d'état français de pédicure-podologue", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession de pédicure-podologue", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Capacité de médecine de gérontologie", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Auxiliaire de puériculture D.E.", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: AP"),
    ("Baccalauréat général", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Baccalauréat professionnel", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BAFA", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BEATEP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BEP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BTS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Brevet des Collèges", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("C.P. surveillant de nuit qualifié", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAFDES", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAFERUIS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAFIME", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CFP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CFP M138", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CPNE", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DAEU-A", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DALF C1", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DE", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEES", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEFA", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEME", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DESS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEUST", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DPLG", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DU RESMS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DUT", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Licence", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Licence Pro", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Maitre apprentissage", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Maitrise", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Manipulateur d'électroradiologie médicale", "Personnel médical: true, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Master", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Master 1", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Master 2", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: ")
;

-- On nisère les postes --
INSERT INTO `postes` (`Intitule_Postes`, `Intitule_Feminin_Postes`) VALUES
    ("A.SOCIAL SPEC.ENFANCE INADAPT.", "ASSISTANTE SOCIALE SPEC.ENFANCE INADAPT."),
    ("ACCOMPAGNANT EDUCATIF SOCIAL", "ACCOMPAGNANTE EDUCATIVE ET SOCIAL"),
    ("ACCUEILLANT SOCIAL", "ACCUEILLANTE SOCIALE"),
    ("ADJ. RESPONSABLE SERV. ECONOM.", "ADJOINTE RESPONSABLE DES SERVICES ECONOMIQUES"),
    ("AGENT ADMINISTRATIF", "AGENTE ADMINISTRATIVE"),
    ("AGENT ADMINISTRATIF PRINCIPAL", "AGENTE ADMINISTRATIVE PRINCIPAL"),
    ("AGENT DE MAINTENANCE", "AGENTE DE MAINTENANCE"),
    ("AGENT DE SERVICE HOSPITALIER", "AGENTE DE SERVICE HOSPITALIER"),
    ("AGENT DE SOINS", "AGENT DE SOINS"),
    ("AGENT DES SERVICES DE SECURITE", "AGENTE DES SERVICES DE SECURITE"),
    ("AGENT DES SERVICES DE SOINS", "AGENTE DES SERVICES DE SOINS"),
    ("AGENT DES SERVICES TECHNIQUES", "AGENTE DES SERVICES TECHNIQUES"),
    ("AGENT HOTELIER SPECIALISE", "AGENTE HOTELIERE SPECIALISEE"),
    ("AGENT SERVICES LOGISTIQUES N1", "AGENTE SERVICES LOGISTIQUES N1"),
    ("AGENT SERVICES LOGISTIQUES N2", "AGENTE SERVICES LOGISTIQUES N2"),
    ("AIDE MEDICO PSYCHOLOGIQUE", "AIDE MEDICO PSYCHOLOGIQUE"),
    ("AIDE-SOIGNANT", "AIDE-SOIGNANTE"),
    ("ANIMATEUR", "ANIMATRICE"),
    ("ANIMATEUR 1ERE CATEGORIE", "ANIMATRICE 1ERE CATEGORIE"),
    ("ANIMATEUR 2EME CATEGORIE", "ANIMATRICE 2EME CATEGORIE"),
    ("ANIMATEUR SOCIO-CULTUREL", "ANIMATRICE SOCIO-CULTUREL"),
    ("ANIMATEUR SOCIO-EDUCATIF", "ANIMATRICE SOCIO-EDUCATIVE"),
    ("ANIMATEUR SOCIO-EDUCATIF N1", "ANIMATRICE SOCIO-EDUCATIVE N1"),
    ("APPRENTI", "APPRENTIE"),
    ("ASSISTANT ADMINISTRATIF", "ASSISTANTE ADMINISTRATIVE"),
    ("ASSISTANT GESTIONNAIRE DE FLUX", "ASSISTANTE GESTIONNAIRE DE FLUX"),
    ("ASSISTANT QUALITE", "ASSISTANTE QUALITE"),
    ("ASSISTANT SOCIAL", "ASSISTANTE SOCIALE"),
    ("ASSISTANT FORMATION", "ASSISTANTE FORMATION"),
    ("AUMONIERE", "AUMONIER"),
    ("AUXILIAIRE DE PUERICULTURE", "AUXILIAIRE DE PUERICULTURE"),
    ("AUXILIAIRE DE VIE", "AUXILIAIRE DE VIE"),
    ("AUXILIAIRE DE VIE DIPLÔME", "AUXILIAIRE DE VIE DIPLOMEE"),
    ("AUXILIAIRE SOCIO - EDUCATIF", "AUXILIAIRE SOCIO - EDUCATIF"),
    ("BIOLOGISTE MEDICAL", "BIOLOGISTE MEDICAL"),
    ("BRANCARDIER", "BRANCARDIERE"),
    ("CADRE ADMINISTRA.ET DE GESTION", "CADRE ADMINISTRA.ET DE GESTION"),
    ("CADRE ADMINISTRATIF NIVEAU 1", "CADRE ADMINISTRATIVE NIVEAU 1"),
    ("CADRE ADMINISTRATIF NIVEAU 3", "CADRE ADMINISTRATIVE NIVEAU 3"),
    ("CADRE COORDINATEUR DES SOINS", "CADRE COORDINATRICE DES SOINS"),
    ("CADRE COORDINATEUR EN HYGIENE", "CADRE COORDINATRICE EN HYGIENE"),
    ("CADRE DE GESTION DES SOINS", "CADRE DE GESTION DES SOINS"),
    ("CADRE DE SANTE", "CADRE DE SANTE"),
    ("CADRE ENSEIGNEMENT DE SANTE", "CADRE ENSEIGNEMENT DE SANTE"),
    ("CADRE INFIRMIER", "CADRE INFIRMIERE HYGIENISTE"),
    ("CADRE INFIRMIER HYGIENISTE", "CADRE INFIRMIERE HYGIENISTE"),
    ("CADRE INFORMATICIEN NIVEAU 2", "CADRE INFORMATICIENNE NIVEAU 2"),
    ("CADRE LOGISTIQUE", "CADRE LOGISTIQUE"),
    ("CADRE MEDICO-TECHNIQUE", "CADRE MEDICO-TECHNIQUE"),
    ("CADRE TECHNIQUE", "CADRE TECHNIQUE"),
    ("CHARGE DE COMMUNICATION", "CHARGEE DE COMMUNICATION"),
    ("CHARGÉ DE PROJETS/DEV.FORMAT.P", "CHARGEE DE PROJETS/DEV.FORMAT.P"),
    ("CHEF COMPTABLE", "CHEFFE COMPTABLE"),
    ("CHEF DE BUREAU", "CHEFFE DE BUREAU"),
    ("CHEF DE CUISINE", "CHEFFE DE CUISINE"),
    ("CHEF DE SER. TECH. BIOMEDICAL", "CHEFFE DE SER. TECH. BIOMEDICAL"),
    ("CHEF DE SERVICE", "CHEFFE DE SERVICE"),
    ("CHEF DE SERVICE ADJOINT", "CHEFFE DE SERVICE ADJOINT"),
    ("CHEF DE SERVICE ADM. NIVEAU 2", "CHEFFE DE SERVICE ADM. NIVEAU 2"),
    ("CHEF DU SERVICE ENTRETIEN", "CHEFFE DU SERVICE ENTRETIEN"),
    ("CHEF SERV.EDUC.CLASSE2 NIV3", "CHEFFE SERV.EDUC.CLASSE2 NIV4"),
    ("COMPTABLE", "COMPTABLE"),
    ("CONSEILLER EN ECO.SOC.ET FAM.", "CONSEILLERE EN ECO.SOC.ET FAM."),
    ("CONSEILLER EN INSERTION", "CONSEILLERE EN INSERTION"),
    ("CONTRAT PROF. AS", "CONTRAT PROF. AS"),
    ("CONTROLEUR DE GESTION N1", "CONTROLEUR DE GESTION N2"),
    ("COORDINAT. QUALITE ET RISQUES", "COORDINATRICE QUALITE ET RISQUES"),
    ("COORDINATEUR GENER. DES SOINS", "COORDINATRICE GENER. DES SOINS"),
    ("COORDINATEUR VIE SOC./HOTEL.", "COORDINATRICE VIE SOC./HOTEL."),
    ("COORDONNATEUR MEDICAL", "COORDONNATEUR MEDICAL"),
    ("DIETETICIENNE", "DIETETICIENNE"),
    ("DIRECTEUR", "DIRECTRICE"),
    ("DIRECTEUR DELEGUE LABO", "DIRECTRICE DELEGUEE LABO"),
    ("DIRECTEUR DES SERVICES", "DIRECTRICE DES SERVICES"),
    ("DIRECTEUR DES SERVICES INFORM.", "DIRECTRICE DES SERVICES INFORM."),
    ("DIRECTEUR FINANCIER", "DIRECTRICE FINANCIER"),
    ("DIRECTEUR FONCTIONNEL", "DIRECTRICE FONCTIONNEL"),
    ("DIRECTEUR GENERAL", "DIRECTRICE GENERAL"),
    ("DIRECTEUR LABORATOIRE", "DIRECTRICE LABORATOIRE"),
    ("DIRECTEUR ORGANIS. ET QUALITE", "DIRECTRICE ORGANIS. ET QUALITE"),
    ("DIRECTEUR RESSOURCES HUMAINES", "DIRECTRICE RESSOURCES HUMAINES"),
    ("DIRECTEUR SERVICES DE SOINS", "DIRECTRICE SERVICES DE SOINS"),
    ("DIRECTEUR SERVICES ECONOMIQUES", "DIRECTRICE SERVICES ECONOMIQUES"),
    ("DIRECTEUR-ADJOINT", "DIRECTRICE-ADJOINTE"),
    ("DIRECTRICE ADJOINTE RH", "DIRECTRICE ADJOINTE RH"),
    ("DIRECTRICE COMMUN. ET ARCHIVES", "DIRECTRICE COMMUN. ET ARCHIVES"),
    ("DIRECTRICE DES SOINS", "DIRECTRICE DES SOINS"),
    ("EDUCATEUR SPECIALISE", "EDUCATRICE SPECIALISEE"),
    ("EDUCATEUR SPORTIF", "EDUCATRICE SPORTIVE"),
    ("EDUCATEUR TECHNIQUE", "EDUCATRICE TECHNIQUE"),
    ("EDUCATEUR TECHNIQUE SPECIALISE", "EDUCATRICE TECHNIQUE SPECIALISEE"),
    ("EDUCATEUR", "EDUCATRICE"),
    ("EDUCATRICE SPECIALISEE", "EDUCATRICE SPECIALISEE"),
    ("EMPLOYE", "EMPLOYEE"),
    ("EMPLOYE ADMINISTRATIF", "EMPLOYEE ADMINISTRATIVE."),
    ("EMPLOYE D\'ACCUEIL ET COMMUNICATION", "EMPLOYEE D\'ACCUEIL ET COMMUNICATION"),
    ("EMPLOYE ADM. AIDE COMPTABLE", "EMPLOYEE ADM. AIDE COMPTABLE"),
    ("ENCADRANT D\'UNITÉ DE SOINS", "ENCADRANTE D\'UNITÉ DE SOINS"),
    ("ENCADRANT MEDICO-TECHNIQUE", "ENCADRANTE MEDICO-TECHNIQUE"),
    ("ENCADRANT UNITE DE REEDUCATION", "ENCADRANTE UNITE DE REEDUCATION"),
    ("ENSEIGNANT INSTITUT FORMATION", "ENSEIGNANTE INSTITUT FORMATION"),
    ("ENSEIGNANT SPECIALISE", "ENSEIGNANTE SPECIALISEE"),
    ("ERGOTHERAPEUTE", "ERGOTHERAPEUTE"),
    ("ETUDIANT", "ETUDIANTE"),
    ("FORMATEUR IFSI", "FORMATRICE IFSI"),
    ("HÔTE DE RESTAURATION", "HÔTESSE DE RESTAURATION"),
    ("INF. SPEC. ANESTHESISTE DE", "INF. SPEC. ANESTHESISTE DE"),
    ("INF. SPEC. BLOC OP DE", "INF. SPEC. BLOC OP DE"),
    ("INF.SPE. PUER DE", "INF.SPE. PUER DE"),
    ("INFIRMIER MAJOR", "INFIRMIERE MAJOR"),
    ("INFIRMIER CHEF", "INFIRMIERE CHEFFE"),
    ("INFIRMIER DE", "INFIRMIERE DE"),
    ("INFIRMIER HYGIENISTE", "INFIRMIERE HYGIENISTE"),
    ("INFORMATICIEN", "INFORMATICIENNE"),
    ("INTERNE", "INTERNE"),
    ("MAGASINIER", "MAGASINIERE"),
    ("MAITRE DE MAISON", "MAITRESSE DE MAISON"),
    ("MANIPULATEUR EN ELECTRO-RADIOL", "MANIPULATRICE EN ELECTRO-RADIOL"),
    ("MASSEUR KINE CHEF DE GROUPE", "MASSEUSE KINE CHEF DE GROUPE"),
    ("MASSEUR-KINESITHERAPEUTE", "MASSEUSE-KINESITHERAPEUTE"),
    ("MEDECIN ASSIST. NON SPECIALISE", "MEDECIN ASSIST. NON SPECIALISEE"),
    ("MEDECIN ASSISTANT", "MEDECIN ASSISTANTE"),
    ("MEDECIN ASSISTANT SPECIALISE", "MEDECIN ASSISTANTE SPECIALISEE"),
    ("MEDECIN ATTACHE", "MEDECIN ATTACHE"),
    ("MEDECIN GENERALISTE", "MEDECIN GENERALISTE"),
    ("MEDECIN SPECIALISE", "MEDECIN SPECIALISE"),
    ("MEDECIN SPECIALISTE", "MEDECIN SPECIALISTE"),
    ("MEDECIN VACATAIRE", "MEDECIN VACATAIRE"),
    ("MEDECIN-BIOLOGISTE", "MEDECIN-BIOLOGISTE"),
    ("MONITEUR ADJOINT D\'ACTIVITES", "MONITRICE ADJOINTE D\'ACTIVITES"),
    ("MONITEUR D\'ATELIER", "MONITRICE D\'ATELIER"),
    ("MONITEUR-EDUCATEUR", "MONITRICE-EDUCATEUR"),
    ("MONITEUR IFAS", "MONITRICE IFAS"),
    ("ORTHOPHONISTE", "ORTHOPHONISTE"),
    ("OUVRIER D\'ENTRETIEN", "OUVRIERE D\'ENTRETIEN"),
    ("OUVRIER HAUT. QUALIFIE", "OUVRIERE HAUT. QUALIFIEE"),
    ("OUVRIER SERV.LOGISTIQUES N1", "OUVRIERE SERV.LOGISTIQUES N1"),
    ("OUVRIER SERV.LOGISTIQUES N2", "OUVRIERE SERV.LOGISTIQUES N2"),
    ("PHARMACIEN BIOLOGISTE DELEGUE", "PHARMACIENNE BIOLOGISTE DELEGUEE"),
    ("PHARMACIEN CHEF DE SERVICE", "PHARMACIENNE CHEFFE DE SERVICE"),
    ("PHARMACIEN", "PHARMACIENNE"),
    ("PREPARATEUR EN PHARMACIE", "PREPARATRICE EN PHARMACIE"),
    ("PREPARATRICE EN PHARMACIE", "PREPARATRICE EN PHARMACIE"),
    ("PSYCHIATRE", "PSYCHIATRE"),
    ("PSYCHOLOGUE", "PSYCHOLOGUE"),
    ("PSYCHOMOTRICIEN(NE)", "PSYCHOMOTRICIEN(NE)"),
    ("RADIO-PHARMACIEN", "RADIO-PHARMACIEN"),
    ("REDACTEUR", "REDACTEUR"),
    ("REFERENT ACCOMP. JURIDIQUE", "REFERENTE ACCOMP. JURIDIQUE"),
    ("REFERENT ASL", "REFERENTE ASL"),
    ("REFERENT TECHNIQUE", "REFERENTE TECHNIQUE"),
    ("RESP. QUALITE ET GEST. RISQUES", "RESP. QUALITE ET GEST. RISQUES"),
    ("RESPONSABLE ADJOINTE ACCUEIL", "RESPONSABLE ADJOINTE ACCUEIL"),
    ("RESPONSABLE ADM. ET FINANCIER", "RESPONSABLE ADM. ET FINANCIER"),
    ("RESPONSABLE DE LA MAINTENANCE", "RESPONSABLE DE LA MAINTENANCE"),
    ("RESPONSABLE HOTELIER", "RESPONSABLE HOTELIER"),
    ("RESPONSABLE INFIRMIER", "RESPONSABLE INFIRMIER"),
    ("RESPONSABLE LOGISTIQUE NIV.1", "RESPONSABLE LOGISTIQUE NIV.1"),
    ("RESPONSABLE LOGISTIQUE NIV.2", "RESPONSABLE LOGISTIQUE NIV.2"),
    ("RESPONSABLE LOGISTIQUE NIV.3", "RESPONSABLE LOGISTIQUE NIV.3"),
    ("RESPONSABLE SECRETARIAT MEDIC.", "RESPONSABLE SECRETARIAT MEDIC."),
    ("RESPONSABLE SERVICE ACCUEIL", "RESPONSABLE SERVICE ACCUEIL"),
    ("RESPONSABLE SERVICE TECHNIQUE", "RESPONSABLE SERVICE TECHNIQUE"),
    ("RESPONSABLE TRAVAUX", "RESPONSABLE TRAVAUX"),
    ("SAGE FEMME", "SAGE FEMME"),
    ("SAGE FEMME CHEF", "SAGE FEMME CHEFFE"),
    ("SECRETAIRE", "SECRETAIRE"),
    ("SECRETAIRE D\'ACCUEIL", "SECRETAIRE D\'ACCUEIL"),
    ("SECRETAIRE DE DIRECTION", "SECRETAIRE DE DIRECTION"),
    ("SECRETAIRE MEDICALE", "SECRETAIRE MEDICALE"),
    ("STAGIAIRE", "STAGIAIRE"),
    ("SURVEILLANT DE NUIT", "SURVEILLANTE DE NUIT"),
    ("SURVEILLANT DE NUIT QUALIFIE", "SURVEILLANTE DE NUIT QUALIFIEE"),
    ("SURVEILLANT GENERAL", "SURVEILLANTE GENERALE"),
    ("TECHN.DES SERV.LOGISTIQUES", "TECHN.DES SERV.LOGISTIQUES"),
    ("TECHNICIEN", "TECHNICIENNE"),
    ("TECHNICIEN ADMINISTRATIF", "TECHNICIENNE ADMINISTRATIVE"),
    ("TECHNICIEN BIOMEDICAL", "TECHNICIENNE BIOMEDICAL"),
    ("TECHNICIEN DE LABORATOIRE", "TECHNICIENNE DE LABORATOIRE"),
    ("TECHNICIEN DE LABORATOIRE CHEF", "TECHNICIENNE DE LABORATOIRE CHEF"),
    ("TECHNICIEN INFORMATION MEDICAL", "TECHNICIENNE INFORMATION MEDICAL"),
    ("TECHNICIEN INFORMATIQUE", "TECHNICIENNE INFORMATIQUE"),
    ("TECHNICIEN SUPERIEUR", "TECHNICIENNE SUPERIEUR"),
    ("TRAVAILLEUR SOCIAL", "TRAVAILLEUSE SOCIAL"),
    ("TRESORIER ADJOINT", "TRESORIERE ADJOINTE"),
    ("FORMATEUR", "FORMATRICE"),
    ("FF D\'INTERNE EN PHARMACIE", "FF D\'INTERNE EN PHARMACIE")
;


-- On insère les aides au recrutement --
INSERT INTO Aides_au_recrutement (Intitule_Aides_au_recrutement) VALUES 
    ("Bourse d'étude"),
    ("Rachat de frais d'étude"),
    ("Prime de cooptation"),
    ("Rachat de contrat")
;
-- On insère les types de contrats --
INSERT INTO Types_de_contrats (Intitule_Types_de_contrats, Description_Types_de_contrats) VALUES 
    ('CDI', 'Contrat à durée indéterminée'), 
    ('CDD', 'Contrat à durée déterminée'), 
    ('Stage', 'Stage en entreprise'),
    ('Alternance', 'Formation réalisée en alternance'), 
    ('Interim', 'Mission réalisé par un prestatère')
;
-- On insère les sources --
INSERT INTO sources (Intitule_Sources) VALUES 
	('Hellowork'), 
    ('Hublo'),
    ('Email'), 
    ('Téléphone')
;   

-- On insère les différents Roles des Utilisateurs --
INSERT INTO Roles (Intitule_Role) VALUES
    ('Propriétaire'),
    ('Administrateur'),
    ('Modérateur'),
    ('Utilisateur'),
    ('Invité')
;
-- On insère les types d'actions des Utilisateurs --
INSERT INTO Types (Intitule_Types) VALUES 
    -- Connexions --
    ('Connexion'),
    ('Déconnexion'), 

    -- Utilisateurs --
    ('Nouvel utilisateur'),
    ('Mise-à-jour utilisateur'), 
    ('Mise-à-jour mot de passe'), 
    ('Réinitialisation mot de passe'), 
    ('Mise-à-jour rôle'), 

    -- candidats --
    ('Nouveau candidat'),
    ('Nouveau rendez-vous'), 
    ('Annulation rendez-vous'), 
    ('Mise-à-jour candidat'), 
    ('Mise-à-jour notation'), 
    ('Mise-à-jour rendez-vous'),

    -- Candidatures -- 
    ('Nouvelle candidature'), 
    ('Nouvelle proposition'), 
    ('Nouveau contrat'), 
    ('Refus candidature'), 
    ('Refus proposition'), 
    ('Démission'), 
    
    -- Fondation --
    ('Nouveau pôle'), 
    ('Nouveau service'), 
    ('Nouvel établissement'), 
    ('Nouveau poste'), 
    ('Nouveau diplome')
;

-- On insère un Utilisateur --
INSERT INTO Utilisateurs (Identifiant_Utilisateurs, Nom_Utilisateurs, Prenom_Utilisateurs, MotDePasse_Utilisateurs, Email_Utilisateurs, Cle_Roles, Cle_Etablissements) VALUES
    ('owner', 'Service informatique', 'Directeur', '$2y$10$GxE1ZTjltfUerJDABRgtLOif/jT1Xpo28CLxb9P./pcvKWJXYis6y', 'yannick.keller@diaconat-mulhouse.fr', 1, 1)
;    