-- Features Toggle --
INSERT INTO Features (Id, Titled, Description, Enable) VALUES 
    (1, "Connexion", "Fonctionnalité permettant la connexion et la déconnexion des utilisateurs.", 1),

    -- Candidates -- 
    (2, "Affichage candidat", "Fonctionnalités permettant la consultation des profils candidats.", 1),                             -- new --
    (3, "Affichage candidats", "Fonctionnalités permettant la consultation de la liste des candidats.", 1),                        -- new --
    (4, "Affichage candiatures", "Fonctionnalités permettant la consultation de la liste des candidatures.", 1),                   -- new --

    (5, "Inscription candidat", "Fonctionnalité permettant l'ajout de nouveaux candidats.", 1),
    (6, "Inscription contrat", "Fonctionnalité permettant l'ajout de nouveaux contrats.", 1),
    (7, "Inscription offre", "Fonctionnalité permettant l'ajout de nouvelles offres d'emplois.", 1),
    (8, "Inscription candidature", "Fonctionnalité permettant l'ajout de nouvelles candidatures.", 1),
    (9, "Inscription rendez-vous", "Fonctionnalité permettant l'ajout de nouveaux rendez-vous.", 1),
    (10, "Inscription document", "Fonctionnalité permettant l'ajout de nouveaux documents.", 1),

    (11, "Edition candidat", "Fonctionnalité permettant la mise à jour de candidats.", 1),
    (12 ,"Edition notation", "Fonctionnalité permettant la mise à jour de la notation des candidats.", 1),
    (13, "Edition contrat", "Fonctionnalité permettant la mise à jour de contrats.", 1),
    (14, "Edition offre", "Fonctionnalité permettant la mise à jour d'offres.", 1),
    (15, "Edition candidature", "Fonctionnalité permettant la mise à jour de candidatures.", 1),
    (16, "Edition rendez-vous", "Fonctionnalité permettant la mise à jour de rendez-vous.", 1),
    (17, "Edition documents", "Fonctionnalité permettant la mise à jour de documents.", 1),

    (18, "Suppression candidat", "Fonctionnalité permettant la suppression de candidats.", 1),
    (19, "Suppression rendez-vous", "Fonctionnalité permettant la suppression de rendez-vous.", 1),
    (20, "Suppression documents", "Fonctionnalité permettant la suppression de documents.", 1),

    (21, "Gestion contrat", "Fonctionnalité permettant l'acceptation et le refus de contrat.", 1),
    (22, "Gestion offre", "Fonctionnalité permettant l'acceptation et le refus d'offres.", 1),
    (23, "Gestion candidature", "Fonctionnalité permettant l'acceptation et le refus de candidature.", 1),

    -- Users --
    (24, "Affichage utilisateur", "Fonctionnalité permettant la consultation des profils utilisateur.", 0),                        -- new --
    (25, "Affichage utilisateurs", "Fonctionnalité permettant la consultation de la liste des utilisateur.", 0),                   -- new --
    (26, "Affiche journal connexions", "Fonctionnalité permettant la consultation des journaux de connexions.", 0),                -- new --
    (27, "Affiche journal actions", "Fonctionnalité permettant la consultation des journaux d'actions.", 0),                       -- new --
    
    (28, "Inscription utilisateur", "Fonctionnalité permettant l'ajout de nouveaux utilisateurs.", 0),                             -- new --
    (29, "Edition utilisateur", "Fonctionnalité permettant la mise à jour des utilisateurs.", 0),                                  -- new --
    (30, "Suppression utilisateur", "Fonctionnalité permettant la suppression des utilisateurs.", 0),                              -- new --

    -- Recruitement --
    (31, "Affichage emplois", "Fonctionnalité permettant la consultation de la liste des emplois.", 0),                            -- new --
    (32, "Affichage qualifications", "Fonctionnalité permettant la consultation de la liste des qualifications.", 0),              -- new --
    (33, "Affichage sources", "Fonctionnalité permettant la consultation de la liste des sources", 0),                             -- new --
    
    (34, "Inscription emplois", "Fonctionnalité permettant l'ajout de nouveaux emplois.", 0),                                      -- new --
    (35, "Inscription qualifications", "Fonctionnalité l'ajout de nouvelles qualifications.", 0),                                  -- new --
    (36, "Inscription sources", "Fonctionnalité permettant l'ajout de nouvelles sources.", 0),                                     -- new --

    (37, "Edition emplois", "Fonctionnalité permettant la mise à jour d'emplois.", 0),                                             -- new --
    (38, "Edition qualifications", "Fonctionnalité permettant la mise à jour de qualifications.", 0),                              -- new --
    (39, "Edition sources", "Fonctionnalité permettant la mise à jour de sources.", 0),                                            -- new --

    -- Foundation --
    (40, "Affichage services", "Fonctionnalité permettant la consultation de la liste des services", 0),                           -- new --
    (41, "Affichage étabmissements", "Fonctionnalité permettant la consultation de la liste des établissements", 0),               -- new --
    (42, "Affichage pôles", "Fonctionnalité permettant la consultation de la liste des pôles.", 0),                                -- new --

    (43, "Inscription services", "Fonctionnalité permettant l'ajout de services.", 0),                                             -- new --
    (44, "Inscription établissement", "Fonctionnalité permettant l'ajout d'établissement.", 0),                                    -- new --
    (45, "Inscription pôles", "Fonctionnalité permettant l'ajout de pôles.", 0),                                                   -- new --

    (46, "Edition services", "Fonctionnalité permettant la mise à jour de services.", 0),                                          -- new --
    (47, "Edition établissements", "Fonctionnalité permettant la mise à jour d'établissements.", 0),                               -- new --
    (48, "Edition pôles", "Fonctionnalité permettant la mise à jour de pôles.", 0),                                                -- new --

    (49, "Insertion données", "Fonctionnalité permettant l'insertion de données dans la base de données.", 0),                     -- new --

    (50, "Gestion mot de passe", "Fonctionnalité permettant aux utilisateurs de modifier leur mot de passe", 0),                   -- new --
    (51, "Réinitialisation mot de passe", "Fonctionnalité permettant aux administrateurs de réinitialiser les mots de passes", 0)  -- new --
;

-- Fondation --
INSERT INTO Poles (Titled, Description) VALUES 
    ("pspdsa", "Pole sud-Alsace"),
    ("pspdca", "Pole centre-Alsace"),
    ("pspdna", "Pole nord-Alsace")
;
INSERT INTO Establishments (Titled, Address, City, PostCode, Key_Poles) VALUES
    ("Clinique du Diaconat Roosevelt", "14 boulevard Roosevelt", "MULHOUSE", 68100, 1),
    ("Clinique du Diaconat Fonderie", "1 rue Saint Sauveur", "MULHOUSE", 68054, 1),
    ("Hôpital Albert Schweitzer", "201 Avenue d'Alsace", "COLMAR", 68000, 2),
    ("Clinique du Diaconat Colmar", "18 rue Charles Sandheer", "COLMAR", 68000, 2),
    ("Hôpital le Neuenberg", "38 rue Pasteur Hermann", "INGWILLER", 67340, 3),
    ("Saint Jean soins de suite", "1 Grande rue", "SENTHEIM", 68780, 1),
    ("CSMRA Château Walk", "1 rue du château Walk", "HAGUENAU", 67500, 3),
    ("Home du Florimont", "1 rue de la promenade", "INGERSHEIM", 68040, 2),
    ("Diaconat Domisoins", "2 rue Jean Schlumberger", "GUEBWILLER", 68500, 1),
    ("Foyer de l'adolescent", "114 route de Lyon", "ILLKIRCH GRAFFENSTADEN", 67400, 3),
    ("EHPAD Notre Dame des Apôtres", "34 rue Bartholdi", "COLMAR", 68000, 2),
    ("Solidarités Adultes et Familles", "89 Avenue de Colmar", "STRASBOURG", 67100, 2),
    ("Maison de retraite Saint Joseph", "10 rue de l'Abbé Bidaine", "GIROMAGNY", 90200, NULL),
    ("EHPAD les Violettes", "22 Faubourg de Mulhouse", "KINGERSHEIM", 68260, 1)
;
INSERT INTO Services (Titled, Description) VALUES 
    ("ACCUEIL", "Service d'accueil général des visiteurs et patients"),
    ("ACCUEIL 3", "Troisième unité d'accueil"),
    ("ACCUEIL INSCRIP ADMISSION", "Accueil et inscription pour l'admission des patients"),
    ("ACCUEIL-STANDARD", "Service d'accueil et gestion des appels téléphoniques"),
    ("ADMINISTRATION", "Service général de gestion administrative"),
    ("Administration", "Gestion des procédures administratives courantes"),
    ("ADMINISTRATION ENCADREMENT", "Service d'encadrement administratif"),
    ("ADMISSIONS", "Service des admissions hospitalières"),
    ("AHS", "Assistance Hôtelière et Soins"),
    ("AHS MED 1 / 2", "Service d'AHS Médecine, unité 1 et 2"),
    ("AHS MED 3/ USMC / USIC", "Unité de soins intensifs et chirurgie"),
    ("AMBULATOIRE", "Service ambulatoire pour les consultations externes"),
    ("ANESTHESIE", "Service d'anesthésie pour les interventions chirurgicales"),
    ("ARCHIVES", "Service de gestion et stockage des archives"),
    ("AS NUIT SOINS", "Aide-soignant(e) pour les soins de nuit"),
    ("ASH CDD", "Aide-soignant hospitalier en contrat à durée déterminée"),
    ("ASPREMA", "Service d'aspiration et soins respiratoires"),
    ("AUMONERIE", "Service d'aumônerie pour l'assistance spirituelle"),
    ("AUMONERIE DIACONAT", "Aumônerie spécifique au Diaconat"),
    ("BIOMEDICAL", "Service des équipements biomédicaux"),
    ("BIONETTOYAGE", "Service de bionettoyage des locaux"),
    ("BLOC ANGIO", "Bloc opératoire dédié à l'angiologie"),
    ("BLOC OPERATOIRE", "Bloc opératoire principal"),
    ("BRANCARDIER CHIR", "Brancardier pour le service de chirurgie"),
    ("CARDIO A", "Service de cardiologie A"),
    ("CARDIO B", "Service de cardiologie B"),
    ("CARDIOLOGIE", "Service de traitement des maladies cardiaques"),
    ("CDD ADM", "Contrat à durée déterminée administratif"),
    ("CDS PHI", "Centre de soins phi"),
    ("CENTRE DE PERINATALITE", "Centre spécialisé en périnatalité"),
    ("CENTRE RESSOURCE TERRITORIALE", "Centre de ressources pour le territoire"),
    ("CHAUFFEURS", "Service de chauffeurs pour le transport médical"),
    ("CHIR AMBULATOIRE", "Chirurgie ambulatoire pour interventions légères"),
    ("CHIRURGIE 1", "Service de chirurgie, unité 1"),
    ("CHIRURGIE 2", "Service de chirurgie, unité 2"),
    ("CHIRURGIE 3", "Service de chirurgie, unité 3"),
    ("CHIRURGIE 4", "Service de chirurgie, unité 4"),
    ("CHIRURGIE A", "Chirurgie, section A"),
    ("CHIRURGIE B", "Chirurgie, section B"),
    ("CHIRURGIE C", "Chirurgie, section C"),
    ("CHIRURGIE D", "Chirurgie, section D"),
    ("CHIRURGIE E", "Chirurgie, section E"),
    ("COMMINUCATION ARCHIVES", "Service de communication et gestion des archives"),
    ("COMPTABILITE", "Service de comptabilité"),
    ("COMPTABILITE CAISSE", "Comptabilité et gestion des caisses"),
    ("CONCOURS AES", "Concours d'admission aux écoles AES"),
    ("CONSULTATION CANCERO", "Consultation dédiée aux patients atteints de cancer"),
    ("CONSULTATION EXTERNE", "Consultations pour les patients externes"),
    ("CONTROLE DE GESTION", "Service de contrôle de gestion hospitalière"),
    ("CRECHE", "Service de crèche pour le personnel hospitalier"),
    ("DIETETIQUE", "Service de diététique pour le suivi nutritionnel des patients"),
    ("DIETETIQUE CDD", "Service de diététique sous contrat à durée déterminée"),
    ("DIRECTION", "Direction générale de l'établissement"),
    ("DIRECTION DES SOINS", "Direction des soins infirmiers et médicaux"),
    ("DOMISOINS GUEBWILLER", "Soins à domicile à Guebwiller"),
    ("DOMISOINS VIEUX THANN", "Soins à domicile à Vieux Thann"),
    ("DPI", "Dossier patient informatisé"),
    ("DSIO", "Direction des systèmes d'information et de l'organisation"),
    ("ECOLE AMP", "École pour les aides médico-psychologiques"),
    ("ECOLE AP", "École pour les aides-soignants"),
    ("ECOLE AS", "École d'aide-soignants"),
    ("ECOLE FORMATION INTERNE", "École de formation interne pour le personnel médical"),
    ("ECOLE OUTRE MER", "Formation pour les personnels d'outre-mer"),
    ("ECOLE VAE", "Validation des acquis de l'expérience"),
    ("EHPAD BETHANIE", "EHPAD situé à Bethanie"),
    ("EHPAD CHAMP FLEURI", "EHPAD du Champ Fleuri"),
    ("EHPAD EMMAUS", "EHPAD Emmaüs"),
    ("EHPAD ETAGE 1 CLINIQUE", "Premier étage de la clinique EHPAD"),
    ("EHPAD LES VIOLETTES", "EHPAD Les Violettes"),
    ("EHPAD RENE VOGEL", "EHPAD René Vogel"),
    ("EHPAD SIMEON", "EHPAD Siméon"),
    ("EN FORMATION", "Personnel en formation professionnelle"),
    ("ENDOSCOPIE", "Service de diagnostic par endoscopie"),
    ("ENI", "Service ENI (Examens Non-Invasifs)"),
    ("ENTRETIEN CDD", "Service d'entretien sous contrat à durée déterminée"),
    ("EXPLORAT FONCTIONNELLES", "Service d'explorations fonctionnelles"),
    ("FACTURATION", "Service de facturation des soins"),
    ("FAE ILLKIRCH", "Formation à l'aide-soignante d'Illkirch"),
    ("GAP", "Groupe d'aide et prévention"),
    ("GYNECOLOGIE", "Service de gynécologie"),
    ("HABITAT INCLUSIF", "Service d'habitat inclusif pour les patients"),
    ("HOME DU FLORIMONT", "Service de soins au Home du Florimont"),
    ("HOPITAL DE JOUR", "Hôpital de jour pour les consultations"),
    ("HOPITAL DE SEMAINE", "Hôpital de semaine pour les hospitalisations légères"),
    ("HYGIENE HOSPITALIERE", "Service d'hygiène hospitalière"),
    ("IFSI", "Institut de formation en soins infirmiers"),
    ("INFORMATIQUE", "Service informatique"),
    ("INTERVENANTES", "Personnel intervenant en soins"),
    ("KINESITHERAPIE", "Service de kinésithérapie"),
    ("KINESITHERAPIE CDD", "Kinésithérapie sous contrat à durée déterminée"),
    ("KINESITHERAPIE ERGOTHERAPIE", "Kinésithérapie et ergothérapie combinées"),
    ("LABORATOIRE FONDERIE", "Laboratoire de la fonderie"),
    ("LABORATOIRE ROOSEVELT", "Laboratoire Roosevelt"),
    ("LASER DERMATOLOGIQUE", "Service de dermatologie laser"),
    ("LINGERIE", "Service de lingerie hospitalière"),
    ("LINGERIE CDD", "Lingerie sous contrat à durée déterminée"),
    ("LOFT", "Service des lofts médicaux"),
    ("MAGASIN", "Service du magasin hospitalier"),
    ("MAINTENANCE", "Service de maintenance des équipements"),
    ("MATERNITE", "Service de maternité"),
    ("MEDECINE", "Médecine générale"),
    ("MEDECINE 1", "Médecine générale, unité 1"),
    ("MEDECINE 2", "Médecine générale, unité 2"),
    ("MEDECINE 3", "Médecine générale, unité 3"),
    ("MEDECINE GERIATRIQUE", "Médecine gériatrique"),
    ("MEDECINE NUCLEAIRE", "Médecine nucléaire"),
    ("MEDECINE POLYVALENTE", "Médecine polyvalente"),
    ("MR", "Médecine de rééducation"),
    ("NEO NAT", "Néonatologie"),
    ("PAHC AS", "Programme d'accompagnement pour les aides-soignants"),
    ("PC SECURITE", "Poste de contrôle sécurité"),
    ("PEDIATRE", "Service pédiatrique"),
    ("PERSONNEL AIDE SOIGNANT CDD", "Aides-soignants sous contrat à durée déterminée"),
    ("PERSONNEL HOTELIER", "Personnel hôtelier du centre hospitalier"),
    ("PERSONNEL MEDICAL", "Personnel médical général"),
    ("PERSONNEL MEDICAL CDD", "Personnel médical sous contrat à durée déterminée"),
    ("PHARMACIE", "Service de pharmacie hospitalière"),
    ("PHI", "Service PHI (Pharmacie à usage intérieur)"),
    ("PMSI - DIM", "Programme de médicalisation des systèmes d'information"),
    ("PNA CARDIO", "Préparation non activée - service cardiologique"),
    ("PNA SOINS", "Préparation non activée - service de soins"),
    ("PNA SOINS NUIT", "Préparation non activée pour soins de nuit"),
    ("PNEUMOLOGIE", "Service de pneumologie"),
    ("POLICLINIQUE", "Polyclinique pour consultations diverses"),
    ("POOL DE REMPLACEMENT", "Service de remplacement pour les soins"),
    ("POUPONNIERE", "Pouponnière hospitalière"),
    ("PRE-ADMISSIONS", "Service de pré-admissions hospitalières"),
    ("PTLAM COLMAR", "PTLAM à Colmar"),
    ("QUALITE HYGIENE", "Service de qualité et d'hygiène hospitalière"),
    ("RADIOLOGIE", "Service de radiologie"),
    ("RECEPTION LOGISTIQUE", "Réception et gestion logistique des biens hospitaliers"),
    ("RESSOURCES HUMAINES", "Service des ressources humaines"),
    ("RESTAURATION CUISINE", "Service de restauration et cuisine"),
    ("RESTAURATION CUISINE CDD", "Restauration sous contrat à durée déterminée"),
    ("RESTAURATION SALLE+CAFETER.CDD", "Restauration en salle et cafétéria sous CDD"),
    ("RESTAURATION SERV.SALLE+CAFET", "Service en salle et cafétéria"),
    ("SAMNA HAGUENAU", "SAMNA situé à Haguenau"),
    ("SAMNA STRASBOURG", "SAMNA situé à Strasbourg"),
    ("SCES EN COURS DE FERMETURE", "Services en cours de fermeture"),
    ("SEC  ANESTHESIE", "Secrétariat pour le service d'anesthésie"),
    ("SEC BLOC OPERATOIRE", "Secrétariat du bloc opératoire"),
    ("SEC CHIR AMBULATOIRE", "Secrétariat de la chirurgie ambulatoire"),
    ("SEC CHIR DIGESTIVE", "Secrétariat de la chirurgie digestive"),
    ("SEC CHIR VASCULAIRE", "Secrétariat de la chirurgie vasculaire"),
    ("SEC DIABETO", "Secrétariat pour le service de diabétologie"),
    ("SEC ENDOSCOPIE", "Secrétariat du service d'endoscopie"),
    ("SEC ENI", "Secrétariat des examens non-invasifs"),
    ("SEC GERIATRIE", "Secrétariat du service de gériatrie"),
    ("SEC GYNECO", "Secrétariat du service de gynécologie"),
    ("SEC HOP DE JOUR", "Secrétariat de l'hôpital de jour"),
    ("SEC ORTHO", "Secrétariat pour le service orthopédique"),
    ("SEC POLICLINIQUE", "Secrétariat pour la polyclinique"),
    ("SEC RADIO", "Secrétariat du service de radiologie"),
    ("SEC RADIO INTERV", "Secrétariat de radiologie interventionnelle"),
    ("SEC RHUMATOLOGIE", "Secrétariat pour le service de rhumatologie"),
    ("SEC SICS", "Secrétariat pour le SICS"),
    ("SEC USIC", "Secrétariat de l'unité de soins intensifs cardiologiques"),
    ("SECRETARIAT CARDIO", "Secrétariat pour le service de cardiologie"),
    ("SECRETARIAT DE DIRECTION", "Secrétariat général de la direction"),
    ("SECRETARIAT MEDICAL", "Secrétariat médical général"),
    ("SERVICE ECONOMIQUE", "Service de gestion économique hospitalière"),
    ("Service éducatif", "Service éducatif interne pour les jeunes patients"),
    ("SERVICE MEDICAL", "Service médical général"),
    ("SERVICE SOCIAL", "Service d'assistance sociale"),
    ("SERVICE SOIGNANT", "Service de soins aux patients"),
    ("SERVICE SOINS IDE CDD", "Service de soins IDE sous contrat à durée déterminée"),
    ("SERVICES FINANCIERS", "Service de gestion financière"),
    ("SERVICES GENERAUX", "Services généraux pour la gestion quotidienne"),
    ("SERVICES TECHNIQUES", "Services techniques et maintenance"),
    ("SICS DIACONAT", "SICS pour le Diaconat"),
    ("SICS HAS", "SICS pour l'HAS"),
    ("SICS MEDICO SOCIAL", "SICS pour le secteur médico-social"),
    ("SIEGE", "Siège de l'administration centrale"),
    ("SOINS ENCADREMENT", "Encadrement des soins médicaux"),
    ("SSR", "Soins de suite et de réadaptation"),
    ("SSR CARDIO VASCUL RESPIRATOIRE", "SSR spécialisé en cardiologie, vasculaire et respiratoire"),
    ("STERILISATION", "Service de stérilisation des équipements"),
    ("TRAVAUX", "Service des travaux et rénovation hospitalière"),
    ("UNITE DE SURVEILLANCE CONTINUE", "Unité de surveillance continue des patients"),
    ("URGENCES", "Service des urgences hospitalières"),
    ("URGENCES CARDIO", "Urgences cardiologiques"),
    ("USC", "Unité de soins continus"),
    ("USIC", "Unité de soins intensifs en cardiologie"),
    ("USICAR", "Unité de soins intensifs en cardiologie et réanimation"),
    ("USLD BETHANIE", "Unité de soins longue durée à Bethanie"),
    ("USMC", "Unité de soins de médecine continue"),
    ("USSR", "Unité de soins de suite et de réadaptation"),
    ("AHS - LINGERIE", "Service de lingerie de l'hopital Albert Schweitzer"),
    ("AHS - CHIR AMBU", "Chirurgie ambulatoire pour interventions légères de l'hopital Albert Schweitzer"),
    ("AHS - CHIR AMBUL/CHIR2", "Chirurgie de l'hopital Albert Schweitzer"),
    ("AHS - CHIR3/4", "Chirurgie de l'hopital Albert Schweitzer"),
    ("AHS - MED1/2/USIC", ""),
    ("AHS - MED3/USMC", ""),
    ("AHS - SICS HAS", ""),
    ("AHS - SODEXO HAS", ""),
    ("AHS - SODEXO DIACONAT", ""),
    ("AHS - ZONE DIVERS", ""),
    ("ACCUEIL - MR", ""),
    ("USLD", "Unités de soins de longue durée"),
    ("SOINS", "Unités de soins réservées aux petites structures")
;
INSERT INTO Belong_to (Key_Services, Key_Establishments) VALUES
    -- Clinique du Diaconat Roosevelt -- 
    (177, 1),
    (23, 1),
    (13, 1),
    (22, 1),
    (73, 1),
    (24, 1),
    (84, 1),
    (12, 1),
    (174, 1),
    (127, 1),
    (72, 1),
    (38, 1),
    (41, 1),
    (39, 1),
    (40, 1),
    (42, 1),
    (121, 1),
    (122, 1),
    (100, 1),
    (80, 1),
    (30, 1),
    (101, 1),
    (107, 1),
    (106, 1),
    (50, 1),
    (27, 1),
    (183, 1),
    (17, 1),
    (88, 1),
    (89, 1),
    (123, 1),
    (93, 1),
    (92, 1),
    (128, 1),
    (124, 1),
    (47, 1),
    (94, 1),
    (130, 1),
    (81, 1),
    (133, 1),
    (20, 1),
    (169, 1),
    (131, 1),
    (3, 1),
    (119, 1),
    (160, 1),
    (86, 1),
    (61, 1),
    (15, 1),
    (117, 1),
    (43, 1),
    (45, 1),
    (77, 1),
    (132, 1),
    (129, 1),
    (53, 1),
    (7, 1),
    (5, 1),
    (49, 1),
    (87, 1),
    (95, 1),
    (114, 1),

    -- Clinique du Diaconat Fonderie --
    (177, 2),
    (23, 2),
    (13, 2),
    (22, 2),
    (179, 2),
    (83, 2),
    (174, 2),
    (72, 2),
    (34, 2),
    (35, 2),
    (122, 2),
    (100, 2),
    (109, 2),
    (126, 2),
    (25, 2),
    (26, 2),
    (76, 2),
    (120, 2),
    (158, 2),
    (183, 2),
    (182, 2),
    (57, 2),
    (180, 2),
    (181, 2),
    (48, 2),
    (20, 2),
    (169, 2),
    (131, 2),
    (3, 2),
    (119, 2),
    (15, 2),
    (117, 2),
    (14, 2),
    (44, 2),
    (77, 2),
    (129, 2),
    (53, 2),
    (7, 2),
    (5, 2),
    (95, 2),
    (114, 2),

    -- Hôpital Albert Schweitzer --
    (177, 3),
    (23, 3),
    (13, 3),
    (22, 3),
    (73, 3),
    (141, 3),
    (140, 3),
    (146, 3),
    (24, 3),
    (174, 3),
    (72, 3),
    (33, 3),
    (34, 3),
    (35, 3),
    (36, 3),
    (37, 3),
    (142, 3),
    (144, 3),
    (143, 3),
    (80, 3),
    (112, 3),
    (149, 3),
    (105, 3),
    (102, 3),
    (103, 3),
    (104, 3),
    (158, 3),
    (184, 3),
    (183, 3),
    (157, 3),
    (58, 3),
    (74, 3),
    (79, 3),
    (85, 3),
    (186, 3),
    (155, 3),
    (147, 3),
    (151, 3),
    (89, 3),
    (176, 3),
    (93, 3),
    (124, 3),
    (152, 3),
    (156, 3),
    (145, 3),
    (171, 3),
    (153, 3),
    (130, 3),
    (154, 3),
    (51, 3),
    (20, 3),
    (169, 3),
    (131, 3),
    (98, 3),
    (178, 3),
    (111, 3),
    (2, 3),
    (4, 3),
    (8, 3),
    (119, 3),
    (46, 3),
    (68, 3),
    (117, 3),
    (161, 3),
    (14, 3),
    (18, 3),
    (77, 3),
    (132, 3),
    (129, 3),
    (53, 3),
    (167, 3),
    (19, 3),
    (188, 3),
    (189, 3),
    (190, 3),
    (191, 3),
    (192, 3),
    (193, 3),
    (194, 3),
    (195, 3),
    (196, 3),
    (197, 3),
    (10, 3),
    (11, 3),

    -- Clinique du Diaconat Colmar --
    (161, 4),
    (194, 4),
    (196, 4),
    (83, 4),
    (150, 4),
    (72, 4),
    (101, 4),
    (107, 4),
    (27, 4),
    (148, 4),
    (89, 4),
    (170, 4),
    (171, 4),
    (172, 4),
    (175, 4),
    (31, 4),
    (51, 4),
    (169, 4),
    (178, 4),
    (2, 4),
    (4, 4),
    (46, 4),
    (60, 4),
    (61, 4),
    (62, 4),
    (63, 4),
    (64, 4),
    (59, 4),
    (68, 4),
    (70, 4),
    (54, 4),
    (5, 4),
    (168, 4),
    (199, 4),

    -- Hôpital le Neuenberg -- 
    (72, 5),
    (30, 5),
    (101, 5),
    (125, 5),
    (139, 5),
    (185, 5),
    (187, 5),
    (130, 5),
    (133, 5),
    (32, 5),
    (198, 5),
    (4, 5),
    (8, 5),
    (62, 5),
    (65, 5),
    (66, 5),
    (67, 5),
    (71, 5),
    (117, 5),
    (161, 5),
    (44, 5),
    (132, 5),
    (53, 5),
    (159, 5),
    (168, 5),
    (95, 5),
    (21, 5),

    -- Saint Jean soins de suite --
    (72, 6),
    (89, 6),
    (90, 6),
    (91, 6),
    (165, 6),
    (163, 6),
    (164, 6),
    (166, 6),
    (133, 6),
    (134, 6),
    (135, 6),
    (136, 6),
    (51, 6),
    (52, 6),
    (169, 6),
    (99, 6),
    (75, 6),
    (113, 6),
    (115, 6),
    (116, 6),
    (53, 6),
    (5, 6),
    (28, 6),
    (95, 6),
    (96, 6),
    (114, 6),
    (16, 6),

    -- CSMRA Château Walk --
    (72, 7),
    (165, 7),
    (163, 7),
    (164, 7),
    (162, 7),
    (5, 7),

    -- Home du Florimont --
    (72, 8),
    (178, 8),
    (46, 8),
    (68, 8),
    (82, 8),
    (18, 8),

    -- Diaconat Domisoins -- 
    (72, 9), 
    (169, 9), 
    (55, 9), 
    (56, 9), 
    (5, 9), 

    -- Foyer de l'adolescent --
    (72, 10),
    (169, 10),
    (137, 10),
    (138, 10),
    (78, 10),
    (53, 10),

    -- EHPAD Notre Dame des Apôtres -- 
    (72, 11),
    (169, 11),
    (200, 11),

    -- Solidarités Adultes et Familles --
    (72, 12),
    (99, 12),
    (110, 12),
    (87, 12),
    (118, 12),
    (108, 12),
    (29, 12),
    (53, 12),
    (173, 12),

    -- Maison de retraite Saint Joseph --
    (72, 13),
    (200, 13),

    -- EHPAD les Violettes --
    (72, 14),
    (69, 14),
    (53, 14)
;
INSERT INTO Jobs (Titled, TitledFeminin) VALUES
    ("A.SOCIAL SPEC.ENFANCE INADAPT.", "ASSISTANTE SOCIALE SPEC.ENFANCE INADAPT."),
    ("ACCOMPAGNANT EDUCATIF SOCIAL", "ACCOMPAGNANTE EDUCATIVE ET SOCIAL"),
    ("ACCUEILLANT SOCIAL", "ACCUEILLANTE SOCIALE"),
    ("ADJ. RESPONSABLE SERV. ECONOM.", "ADJOINTE RESPONSABLE DES SERVICES ECONOMIQUES"),
    ("AGENT ADMINISTRATIF", "AGENTE ADMINISTRATIVE"),
    ("AGENT ADMINISTRATIF PRINCIPAL", "AGENTE ADMINISTRATIVE PRINCIPAL"),
    ("AGENT DE MAINTENANCE", "AGENTE DE MAINTENANCE"),
    ("AGENT DE SERVICE HOSPITALIER", "AGENTE DE SERVICE HOSPITALIER"),
    ("AGENT DE SOINS", "AGENT DE SOINS"),
    ("AGENT DES SERVICES DE SECURITE", "AGENTE DES SERVICES DE SECURITE"),
    ("AGENT DES SERVICES DE SOINS", "AGENTE DES SERVICES DE SOINS"),
    ("AGENT DES SERVICES TECHNIQUES", "AGENTE DES SERVICES TECHNIQUES"),
    ("AGENT HOTELIER SPECIALISE", "AGENTE HOTELIERE SPECIALISEE"),
    ("AGENT SERVICES LOGISTIQUES N1", "AGENTE SERVICES LOGISTIQUES N1"),
    ("AGENT SERVICES LOGISTIQUES N2", "AGENTE SERVICES LOGISTIQUES N2"),
    ("AIDE MEDICO PSYCHOLOGIQUE", "AIDE MEDICO PSYCHOLOGIQUE"),
    ("AIDE-SOIGNANT", "AIDE-SOIGNANTE"),
    ("ANIMATEUR", "ANIMATRICE"),
    ("ANIMATEUR 1ERE CATEGORIE", "ANIMATRICE 1ERE CATEGORIE"),
    ("ANIMATEUR 2EME CATEGORIE", "ANIMATRICE 2EME CATEGORIE"),
    ("ANIMATEUR SOCIO-CULTUREL", "ANIMATRICE SOCIO-CULTUREL"),
    ("ANIMATEUR SOCIO-EDUCATIF", "ANIMATRICE SOCIO-EDUCATIVE"),
    ("ANIMATEUR SOCIO-EDUCATIF N1", "ANIMATRICE SOCIO-EDUCATIVE N1"),
    ("APPRENTI", "APPRENTIE"),
    ("ASSISTANT ADMINISTRATIF", "ASSISTANTE ADMINISTRATIVE"),
    ("ASSISTANT GESTIONNAIRE DE FLUX", "ASSISTANTE GESTIONNAIRE DE FLUX"),
    ("ASSISTANT QUALITE", "ASSISTANTE QUALITE"),
    ("ASSISTANT SOCIAL", "ASSISTANTE SOCIALE"),
    ("ASSISTANT FORMATION", "ASSISTANTE FORMATION"),
    ("AUMONIERE", "AUMONIER"),
    ("AUXILIAIRE DE PUERICULTURE", "AUXILIAIRE DE PUERICULTURE"),
    ("AUXILIAIRE DE VIE", "AUXILIAIRE DE VIE"),
    ("AUXILIAIRE DE VIE DIPLÔME", "AUXILIAIRE DE VIE DIPLOMEE"),
    ("AUXILIAIRE SOCIO - EDUCATIF", "AUXILIAIRE SOCIO - EDUCATIF"),
    ("BIOLOGISTE MEDICAL", "BIOLOGISTE MEDICAL"),
    ("BRANCARDIER", "BRANCARDIERE"),
    ("CADRE ADMINISTRA.ET DE GESTION", "CADRE ADMINISTRA.ET DE GESTION"),
    ("CADRE ADMINISTRATIF NIVEAU 1", "CADRE ADMINISTRATIVE NIVEAU 1"),
    ("CADRE ADMINISTRATIF NIVEAU 3", "CADRE ADMINISTRATIVE NIVEAU 3"),
    ("CADRE COORDINATEUR DES SOINS", "CADRE COORDINATRICE DES SOINS"),
    ("CADRE COORDINATEUR EN HYGIENE", "CADRE COORDINATRICE EN HYGIENE"),
    ("CADRE DE GESTION DES SOINS", "CADRE DE GESTION DES SOINS"),
    ("CADRE DE SANTE", "CADRE DE SANTE"),
    ("CADRE ENSEIGNEMENT DE SANTE", "CADRE ENSEIGNEMENT DE SANTE"),
    ("CADRE INFIRMIER", "CADRE INFIRMIERE"),
    ("CADRE INFIRMIER HYGIENISTE", "CADRE INFIRMIERE HYGIENISTE"),
    ("CADRE INFORMATICIEN NIVEAU 2", "CADRE INFORMATICIENNE NIVEAU 2"),
    ("CADRE LOGISTIQUE", "CADRE LOGISTIQUE"),
    ("CADRE MEDICO-TECHNIQUE", "CADRE MEDICO-TECHNIQUE"),
    ("CADRE TECHNIQUE", "CADRE TECHNIQUE"),
    ("CHARGE DE COMMUNICATION", "CHARGEE DE COMMUNICATION"),
    ("CHARGÉ DE PROJETS/DEV.FORMAT.P", "CHARGEE DE PROJETS/DEV.FORMAT.P"),
    ("CHEF COMPTABLE", "CHEFFE COMPTABLE"),
    ("CHEF DE BUREAU", "CHEFFE DE BUREAU"),
    ("CHEF DE CUISINE", "CHEFFE DE CUISINE"),
    ("CHEF DE SER. TECH. BIOMEDICAL", "CHEFFE DE SER. TECH. BIOMEDICAL"),
    ("CHEF DE SERVICE", "CHEFFE DE SERVICE"),
    ("CHEF DE SERVICE ADJOINT", "CHEFFE DE SERVICE ADJOINT"),
    ("CHEF DE SERVICE ADM. NIVEAU 2", "CHEFFE DE SERVICE ADM. NIVEAU 2"),
    ("CHEF DU SERVICE ENTRETIEN", "CHEFFE DU SERVICE ENTRETIEN"),
    ("CHEF SERV.EDUC.CLASSE2 NIV3", "CHEFFE SERV.EDUC.CLASSE2 NIV4"),
    ("COMPTABLE", "COMPTABLE"),
    ("CONSEILLER EN ECO.SOC.ET FAM.", "CONSEILLERE EN ECO.SOC.ET FAM."),
    ("CONSEILLER EN INSERTION", "CONSEILLERE EN INSERTION"),
    ("CONTRAT PROF. AS", "CONTRAT PROF. AS"),
    ("CONTROLEUR DE GESTION N1", "CONTROLEUR DE GESTION N2"),
    ("COORDINAT. QUALITE ET RISQUES", "COORDINATRICE QUALITE ET RISQUES"),
    ("COORDINATEUR GENER. DES SOINS", "COORDINATRICE GENER. DES SOINS"),
    ("COORDINATEUR VIE SOC./HOTEL.", "COORDINATRICE VIE SOC./HOTEL."),
    ("COORDONNATEUR MEDICAL", "COORDONNATEUR MEDICAL"),
    ("DIETETICIENNE", "DIETETICIENNE"),
    ("DIRECTEUR", "DIRECTRICE"),
    ("DIRECTEUR DELEGUE LABO", "DIRECTRICE DELEGUEE LABO"),
    ("DIRECTEUR DES SERVICES", "DIRECTRICE DES SERVICES"),
    ("DIRECTEUR DES SERVICES INFORM.", "DIRECTRICE DES SERVICES INFORM."),
    ("DIRECTEUR FINANCIER", "DIRECTRICE FINANCIER"),
    ("DIRECTEUR FONCTIONNEL", "DIRECTRICE FONCTIONNEL"),
    ("DIRECTEUR GENERAL", "DIRECTRICE GENERAL"),
    ("DIRECTEUR LABORATOIRE", "DIRECTRICE LABORATOIRE"),
    ("DIRECTEUR ORGANIS. ET QUALITE", "DIRECTRICE ORGANIS. ET QUALITE"),
    ("DIRECTEUR RESSOURCES HUMAINES", "DIRECTRICE RESSOURCES HUMAINES"),
    ("DIRECTEUR SERVICES DE SOINS", "DIRECTRICE SERVICES DE SOINS"),
    ("DIRECTEUR SERVICES ECONOMIQUES", "DIRECTRICE SERVICES ECONOMIQUES"),
    ("DIRECTEUR-ADJOINT", "DIRECTRICE-ADJOINTE"),
    ("DIRECTRICE ADJOINTE RH", "DIRECTRICE ADJOINTE RH"),
    ("DIRECTRICE COMMUN. ET ARCHIVES", "DIRECTRICE COMMUN. ET ARCHIVES"),
    ("DIRECTRICE DES SOINS", "DIRECTRICE DES SOINS"),
    ("EDUCATEUR SPECIALISE", "EDUCATRICE SPECIALISEE"),
    ("EDUCATEUR SPORTIF", "EDUCATRICE SPORTIVE"),
    ("EDUCATEUR TECHNIQUE", "EDUCATRICE TECHNIQUE"),
    ("EDUCATEUR TECHNIQUE SPECIALISE", "EDUCATRICE TECHNIQUE SPECIALISEE"),
    ("EDUCATEUR", "EDUCATRICE"),
    ("EMPLOYE", "EMPLOYEE"),
    ("EMPLOYE ADMINISTRATIF", "EMPLOYEE ADMINISTRATIVE."),
    ("EMPLOYE D'ACCUEIL ET COMMUNICATION", "EMPLOYEE D'ACCUEIL ET COMMUNICATION"),
    ("EMPLOYE ADM. AIDE COMPTABLE", "EMPLOYEE ADM. AIDE COMPTABLE"),
    ("ENCADRANT D'UNITÉ DE SOINS", "ENCADRANTE D'UNITÉ DE SOINS"),
    ("ENCADRANT MEDICO-TECHNIQUE", "ENCADRANTE MEDICO-TECHNIQUE"),
    ("ENCADRANT UNITE DE REEDUCATION", "ENCADRANTE UNITE DE REEDUCATION"),
    ("ENSEIGNANT INSTITUT FORMATION", "ENSEIGNANTE INSTITUT FORMATION"),
    ("ENSEIGNANT SPECIALISE", "ENSEIGNANTE SPECIALISEE"),
    ("ERGOTHERAPEUTE", "ERGOTHERAPEUTE"),
    ("ETUDIANT", "ETUDIANTE"),
    ("FORMATEUR IFSI", "FORMATRICE IFSI"),
    ("HÔTE DE RESTAURATION", "HÔTESSE DE RESTAURATION"),
    ("INF. SPEC. ANESTHESISTE DE", "INF. SPEC. ANESTHESISTE DE"),
    ("INF. SPEC. BLOC OP DE", "INF. SPEC. BLOC OP DE"),
    ("INF.SPE. PUER DE", "INF.SPE. PUER DE"),
    ("INFIRMIER MAJOR", "INFIRMIERE MAJOR"),
    ("INFIRMIER CHEF", "INFIRMIERE CHEFFE"),
    ("INFIRMIER DE", "INFIRMIERE DE"),
    ("INFIRMIER HYGIENISTE", "INFIRMIERE HYGIENISTE"),
    ("INFORMATICIEN", "INFORMATICIENNE"),
    ("INTERNE", "INTERNE"),
    ("MAGASINIER", "MAGASINIERE"),
    ("MAITRE DE MAISON", "MAITRESSE DE MAISON"),
    ("MANIPULATEUR EN ELECTRO-RADIOL", "MANIPULATRICE EN ELECTRO-RADIOL"),
    ("MASSEUR KINE CHEF DE GROUPE", "MASSEUSE KINE CHEF DE GROUPE"),
    ("MASSEUR-KINESITHERAPEUTE", "MASSEUSE-KINESITHERAPEUTE"),
    ("MEDECIN ASSIST. NON SPECIALISE", "MEDECIN ASSIST. NON SPECIALISEE"),
    ("MEDECIN ASSISTANT", "MEDECIN ASSISTANTE"),
    ("MEDECIN ASSISTANT SPECIALISE", "MEDECIN ASSISTANTE SPECIALISEE"),
    ("MEDECIN ATTACHE", "MEDECIN ATTACHE"),
    ("MEDECIN GENERALISTE", "MEDECIN GENERALISTE"),
    ("MEDECIN SPECIALISE", "MEDECIN SPECIALISE"),
    ("MEDECIN SPECIALISTE", "MEDECIN SPECIALISTE"),
    ("MEDECIN VACATAIRE", "MEDECIN VACATAIRE"),
    ("MEDECIN-BIOLOGISTE", "MEDECIN-BIOLOGISTE"),
    ("MONITEUR ADJOINT D'ACTIVITES", "MONITRICE ADJOINTE D'ACTIVITES"),
    ("MONITEUR D'ATELIER", "MONITRICE D'ATELIER"),
    ("MONITEUR-EDUCATEUR", "MONITRICE-EDUCATEUR"),
    ("MONITEUR IFAS", "MONITRICE IFAS"),
    ("ORTHOPHONISTE", "ORTHOPHONISTE"),
    ("OUVRIER D'ENTRETIEN", "OUVRIERE D'ENTRETIEN"),
    ("OUVRIER HAUT. QUALIFIE", "OUVRIERE HAUT. QUALIFIEE"),
    ("OUVRIER SERV.LOGISTIQUES N1", "OUVRIERE SERV.LOGISTIQUES N1"),
    ("OUVRIER SERV.LOGISTIQUES N2", "OUVRIERE SERV.LOGISTIQUES N2"),
    ("PHARMACIEN BIOLOGISTE DELEGUE", "PHARMACIENNE BIOLOGISTE DELEGUEE"),
    ("PHARMACIEN CHEF DE SERVICE", "PHARMACIENNE CHEFFE DE SERVICE"),
    ("PHARMACIEN", "PHARMACIENNE"),
    ("PREPARATEUR EN PHARMACIE", "PREPARATRICE EN PHARMACIE"),
    ("PSYCHIATRE", "PSYCHIATRE"),
    ("PSYCHOLOGUE", "PSYCHOLOGUE"),
    ("PSYCHOMOTRICIEN(NE)", "PSYCHOMOTRICIEN(NE)"),
    ("RADIO-PHARMACIEN", "RADIO-PHARMACIEN"),
    ("REDACTEUR", "REDACTEUR"),
    ("REFERENT ACCOMP. JURIDIQUE", "REFERENTE ACCOMP. JURIDIQUE"),
    ("REFERENT ASL", "REFERENTE ASL"),
    ("REFERENT TECHNIQUE", "REFERENTE TECHNIQUE"),
    ("RESP. QUALITE ET GEST. RISQUES", "RESP. QUALITE ET GEST. RISQUES"),
    ("RESPONSABLE ADJOINTE ACCUEIL", "RESPONSABLE ADJOINTE ACCUEIL"),
    ("RESPONSABLE ADM. ET FINANCIER", "RESPONSABLE ADM. ET FINANCIER"),
    ("RESPONSABLE DE LA MAINTENANCE", "RESPONSABLE DE LA MAINTENANCE"),
    ("RESPONSABLE HOTELIER", "RESPONSABLE HOTELIER"),
    ("RESPONSABLE INFIRMIER", "RESPONSABLE INFIRMIER"),
    ("RESPONSABLE LOGISTIQUE NIV.1", "RESPONSABLE LOGISTIQUE NIV.1"),
    ("RESPONSABLE LOGISTIQUE NIV.2", "RESPONSABLE LOGISTIQUE NIV.2"),
    ("RESPONSABLE LOGISTIQUE NIV.3", "RESPONSABLE LOGISTIQUE NIV.3"),
    ("RESPONSABLE SECRETARIAT MEDIC.", "RESPONSABLE SECRETARIAT MEDIC."),
    ("RESPONSABLE SERVICE ACCUEIL", "RESPONSABLE SERVICE ACCUEIL"),
    ("RESPONSABLE SERVICE TECHNIQUE", "RESPONSABLE SERVICE TECHNIQUE"),
    ("RESPONSABLE TRAVAUX", "RESPONSABLE TRAVAUX"),
    ("SAGE FEMME", "SAGE FEMME"),
    ("SAGE FEMME CHEF", "SAGE FEMME CHEFFE"),
    ("SECRETAIRE", "SECRETAIRE"),
    ("SECRETAIRE D'ACCUEIL", "SECRETAIRE D'ACCUEIL"),
    ("SECRETAIRE DE DIRECTION", "SECRETAIRE DE DIRECTION"),
    ("SECRETAIRE MEDICALE", "SECRETAIRE MEDICALE"),
    ("STAGIAIRE", "STAGIAIRE"),
    ("SURVEILLANT DE NUIT", "SURVEILLANTE DE NUIT"),
    ("SURVEILLANT DE NUIT QUALIFIE", "SURVEILLANTE DE NUIT QUALIFIEE"),
    ("SURVEILLANT GENERAL", "SURVEILLANTE GENERALE"),
    ("TECHN.DES SERV.LOGISTIQUES", "TECHN.DES SERV.LOGISTIQUES"),
    ("TECHNICIEN", "TECHNICIENNE"),
    ("TECHNICIEN ADMINISTRATIF", "TECHNICIENNE ADMINISTRATIVE"),
    ("TECHNICIEN BIOMEDICAL", "TECHNICIENNE BIOMEDICAL"),
    ("TECHNICIEN DE LABORATOIRE", "TECHNICIENNE DE LABORATOIRE"),
    ("TECHNICIEN DE LABORATOIRE CHEF", "TECHNICIENNE DE LABORATOIRE CHEF"),
    ("TECHNICIEN INFORMATION MEDICAL", "TECHNICIENNE INFORMATION MEDICAL"),
    ("TECHNICIEN INFORMATIQUE", "TECHNICIENNE INFORMATIQUE"),
    ("TECHNICIEN SUPERIEUR", "TECHNICIENNE SUPERIEUR"),
    ("TRAVAILLEUR SOCIAL", "TRAVAILLEUSE SOCIAL"),
    ("TRESORIER ADJOINT", "TRESORIERE ADJOINTE"),
    ("FORMATEUR", "FORMATRICE"),
    ("FF D'INTERNE EN PHARMACIE", "FF D'INTERNE EN PHARMACIE"),
    ("GESTIONNAIRE DE PAIE", "GESTIONNAIRE DE PAIE"),
    ("INFIRMIER COORDINATEUR", "INFIRMIERE COORDINATRICE")
;

-- Recrutement --
INSERT INTO Helps (Titled) VALUES 
    ("Bourse d'étude"),
    ("Rachat de frais d'étude"),
    ("Prime de cooptation"),
    ("Rachat de contrat")
;
INSERT INTO Types_of_contracts (Titled, Description) VALUES 
    ("CDI", "Contrat à durée indéterminée"), 
    ("CDD", "Contrat à durée déterminée"), 
    ("Stage", "Stage en entreprise"),
    ("Alternance", "Formation réalisée en alternance"), 
    ("Interim", "Mission réalisé par un prestatère"),
    ("vacation", "Mission réalisée par un vacataire")
;
INSERT INTO Types_of_sources (Titled) VALUEs 
    ("Autre"),
    ("Interne"),
    ("Interim"),
    ("Platerfome")
;
INSERT INTO Sources (Titled, Key_Types_of_sources) VALUES 
    ("1termed", 3),
    ("Adecco", 3),
    ("Appel Médical", 3),
    ("Camo Gémo", 3),
    ("Candidature interne", 2),
    ("Contact Fondation", 2),
    ("Crit", 3),
    ("Domino RH", 3),
    ("Duo Santé", 3),
    ("Email", 1), 
    ("Ergalis", 3),
    ("France Travail", 4),
    ("Indeed", 4),
    ("Jobergroup", 3),
    ("Job Dating", 4),
    ("Job Fondation", 2),
    ("Job Médical", 4),
    ("JPL Interim", 3),
    ("Harry Hope", 3),
	("Hellowork", 2), 
    ("Hublo", 2),
    ("Les experts de l'emploi", 2),
    ("LinkedIn",2 ),
    ("LHH Recruitment Solutions", 3),
    ("Madeline Recrutement", 3),
    ("Manpower", 3),
    ("Menway", 3),
    ("Profil Santé", 3),
    ("Recommandée", 1),
    ("Salon Emploi Formation", 4),
    ("Satis TT", 3),
    ("Sourcing", 1),
    ("Spontanée", 1),
    ("Talent Santé", 3),
    ("Téléphone", 1),
    ("Vitalis", 3)
;   
INSERT INTO Qualifications (Titled, MedicalStaff, Abreviation) VALUES 
    ("Aide soignant D.E.", TRUE, "A.S."),
    ("Autorisation ministérielle de plein exercice", TRUE, NULL),
    ("Auxiliaire de puériculture D.E.", TRUE, "A.P."),
    ("Baccalauréat général", FALSE, NULL),
    ("Baccalauréat professionnel", FALSE, NULL),
    ("BAFA", FALSE, NULL),
    ("BEATEP", FALSE, NULL),
    ("BEP", FALSE, NULL),
    ("Brevet des Collèges", FALSE, NULL),
    ("BTS", FALSE, NULL),
    ("C.P. surveillant de nuit qualifié", FALSE, NULL),
    ("CAFDES", FALSE, NULL),
    ("CAFERUIS", FALSE, NULL),
    ("CAFIME", FALSE, NULL),
    ("CAP", FALSE, NULL),
    ("Capacité de médecine de gérontologie", TRUE, NULL),
    ("CFP", FALSE, "CFP"),
    ("CFP M138", FALSE, "CFP M138"),
    ("CPNE", FALSE, "CPNE"),
    ("DAEU-A", FALSE, "DAEU-A"),
    ("DALF C1", FALSE, "DALF C1"),
    ("DE", FALSE, NULL),
    ("DEES", FALSE, NULL),
    ("DEFA", FALSE, NULL),
    ("DEME", FALSE, NULL),
    ("DESS", FALSE, NULL),
    ("DEUST", FALSE, NULL),
    ("Diplôme d'Etat de docteur en médecine", TRUE, "Médecin"),
    ("Diplôme d'études spécialisées de médecine générale", TRUE, "Médecin"),
    ("Diplôme d'état français de cadre de santé", TRUE, "C.S."),
    ("Diplôme d'état français de masseur-kinesitherapeute", TRUE, "KINE"),
    ("Diplôme d'état français de pédicure-podologue", TRUE, NULL),
    ("Diplôme d'état français d'infirmier", TRUE, "I.D.E."),
    ("Diplôme d'état français d'infirmier anesthésiste", TRUE, "I.A.D.E."),
    ("Diplôme d'état français d'infirmier de bloc opératoire", TRUE, "I.B.O.D.E."),
    ("Diplôme d'état français d'infirmier puericulteur", TRUE, "I.P."),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession de masseur-kinesitherapeute", TRUE, "KINE"),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession de pédicure-podologue", TRUE, NULL),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession d'infirmier", TRUE, "I.D.E."),
    ("DPLG", FALSE, NULL),
    ("DU RESMS", FALSE, NULL),
    ("DUT", FALSE, NULL),
    ("Licence", FALSE, NULL),
    ("Licence Pro", FALSE, NULL),
    ("Maitre apprentissage", FALSE, NULL),
    ("Maitrise", FALSE, NULL),
    ("Manipulateur d'électroradiologie médicale", TRUE, "M.E.R.M."),
    ("Master", FALSE, NULL),
    ("Master 1", FALSE, NULL),
    ("Master 2", FALSE, NULL),
    ("Sage Femme D.E.", TRUE, "S.F."),
    ("Aide médico-psychologique D.E.", TRUE, "A.M.P."),
    ("Auxiliaire de vie social D.E.", FALSE, "A.V.S."),
    ("Diplôme d'Etat d'Ergothérapeute", TRUE, NULL),
    ("Mention Complétaire Aide à Domicile", FALSE, "M.C.A.D.")
;

-- Users --
INSERT INTO Roles (Titled) VALUES
    ('Propriétaire'),
    ('Administrateur'),
    ('Modérateur'),
    ('Utilisateur'),
    ('Invité')
;
INSERT INTO Types_of_actions (Titled) VALUES 
    -- Connexions --
    ('Connexion'),
    ('Déconnexion'), 

    -- Users --
    ('Nouvel utilisateur'),
    ('Mise à jour utilisateur'), 
    ('Mise à jour mot de passe'), 
    ('Réinitialisation mot de passe'), 
    ('Mise à jour rôle'), 

    -- candidats --
    ('Nouveau candidat'),
    ('Nouveau rendez-vous'), 
    ('Annulation rendez-vous'), 
    ('Mise à jour candidat'), 
    ('Mise à jour notation'), 
    ('Mise à jour rendez-vous'),

    -- Candidatures -- 
    ('Nouvelle candidature'), 
    ('Nouvelle proposition'), 
    ('Nouveau contrat'), 
    ('Refus candidature'), 
    ('Refus proposition'), 
    ('Démission'), 
    
    -- Fondation --
    ('Nouveau pôle'), 
    ('Nouveau service'), 
    ('Nouvel établissement'), 
    ('Nouveau poste'), 
    ('Nouvelle qualification')
;